### ISSUE TITLE
Potential features

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#100]
I am not sure if any of these features are worth implementing. If you care about one of those features very strongly, please open a separate issue on the Github issue tracker. Please explain why it is important, and let me know if you have suggestions for implementation.

- cbind
- Display tables side-by-side
- Fonts
  - Choose font in different languages and scripts
- Format captions and footnotes
- HTML-specific
  - tooltips (kableExtra) 
  - scrollable box
    - Just a wrap the whole table in a div: `<div style="border: 1px solid #ddd; padding: 5px; overflow-y: scroll; height:200px; overflow-x: scroll; width:500px; ">...table...</div>`
  - Column filters (DT, reactable)
  - Sortable columns (reactable)
  - Resizable columns (reactable)
  - Paginated tables (reactable)
  - placement: left, right, center (easy to achieve with CSS, so probably not necessary)
- Rotating text
- Export
  - Custom width, height, and resolution for image export
  - JPG
  - RTF
  - Powerpoint
  - SVG
  - Excel
  - Grob (R grid graphical object)
- Restack
  - huxtable has a function similar to `reshape()`. I'd rather let specialized tools handle this.
- Formatting options
  - `gt` has many `fmt_()` functions, but `tinytable::format_tt()` accepts a `fn` argument, which allows us to leverage many functions such as those in the `scales` package. See the tutorial on the website for examples.

**Comment by aghaynes** [comment]
- [ ] tables that break across pages where necessary (i.e. tables too long for a single page, especially for typst, i think xtable provides this for tex)
