### ISSUE TITLE
First row of tibble ends up in header

### ISSUE THREAD

**Issue by timnehls** [vincentarelbundock/tinytable#106]
When running the following code:
```
load("fit.Rdata")

param_names <- vector("character", 20)

for(i in 0:19) {
  param_names[i + 1] <- str_glue('$\\theta_{<<i>>}$', .open = "<<", .close = ">>")
}

summary(fit)[[1]] %>% 
  as_tibble() %>% 
  select("mean", "sd", "2.5%", "97.5%") %>% 
  head(20) %>% 
  mutate(Parameter = param_names, .before = "mean") %>%
  tt()
``` 

I end up with this table when running in the console (as desired): 
![image](https://github.com/vincentarelbundock/tinytable/assets/93290955/20361aa8-ed85-474f-904b-b1978525efb3)
but when knitting it to PDF, the following happens:
![image](https://github.com/vincentarelbundock/tinytable/assets/93290955/7b793086-7604-4c3f-95af-53d8f3269cf9)

Is this common? Happy for any help...

**Comment by timnehls** [comment]
Sorry, didn't realise I had the % signs in the header. My bad.

**Comment by vincentarelbundock** [comment]
Cool, so you just escaped the characters and it worked?

**Comment by timnehls** [comment]
Yeah, problem solved. Thanks for the package 👍
