### ISSUE TITLE
Default output format has changed from HTML to Markdown when interactive?

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/tinytable#109]
I just updated to tt 0.0.2, and when I now create a table using `tt()`, the default output is the markdown syntax in the console - I believe it was HTML in the viewer pane before, which makes more sense in interactive mode.

Is there something that has changed in this regard?

**Comment by vincentarelbundock** [comment]
I was running into problems in my own setup: Linux running via WSL on Windows. Whenever I printed an HTML table, it opened a weird window which slowed down the whole computer. I could probably fix this, but my conclusion was that it is generally not save to open browser windows unless we are in a controlled environment like RStudio.

So I changed to Markdown as default. Note that you can set the default by:

`options("tinytable_print_output" = "html")`

**Comment by strengejacke** [comment]
Ah, good to know. But isn't markdown an unpractical default, because why would I want a Markdown formatted table in the console?

Furthermore, maybe you could add an `output` argument to `tt()`? From a developers perspective, if I have a `print_html()` method, I would either need to put `print(..., output="HTML")` at the end of the method, which means I cannot further modify the table with other functions from the `tt()` package. If I don't use `print(..., output="HTML")` at the end, the user sees a markdown table in the console although a HTML table is expected.

**Comment by vincentarelbundock** [comment]
It would be trivial for use to define a custom method to print to any output:

```r
class(tab) <- c("ggeffects_tinytable", class(tab))
print.ggeffect_tinytable <- function(x) print(x, "html")
```

I'm hesitant to include an `output` argument in `tt()` because we can only save or print at the very end of the pipeline, once all the modifications have been registered. And I don't want to duplicate the output in `tt()` and `save_tt()`, because that leads to confusion. In `modelsummary`, this is bad because we specify `output` at the start, but that breaks if we then modify the table with `kableExtra` or some other. Maybe I can think of a cool programming trick to delay evaluation, but I can't think of one right now.

**Comment by strengejacke** [comment]
Yeah, the problem is that the _user_ can't do further modifications.
With _tt 0.0.1_, I had a function `print_html()` that just returns the `tinytable` object, which was by default printed as HTML table. However, the user could also do `print_html() |> tt(theme = "grid")` to make own modifications, like you can do with ggplot-objects returned from any `plot()` method that relies on _ggplot2_.

Now, `print_method()` prints a markdown table to the console(!) - I never need the markdown format in the console, I only need it in RMarkdown docs - unless I use `print(x, output = "html")` at the end of my `print_html()` function. Thus, the user can no longer modify the table by adding "layers" with `print_html() |> tt(theme = "grid")`.

So either I force to print as HTML and take away the opportunity for the user for further modifications, or the user has to do something like `print(print_html(...), output = "html")`, which looks a bit awkward from a user perspective?

I'm also thinking of future use cases, I imagine _tinytable_ will get quite some more features, allowing to further customize a `tinytable` object, that's why it would be nice to have an option that the returned `tinytable` object is definitely printed in a specific format.

**Comment by vincentarelbundock** [comment]
Any of your attempts with WSL/Linux?

I get what you mean, but the only option that will not be available is `theme`. All the other functions like `style_tt()` and `format_tt()` should be possible for you.

Also, `gt` doesn't have an output argument in the main function, and the evaluation model is kind of similar: We store all the commands in the object, and only execute them when they are printed or saved at the end. So conceptually and implementation-wise, it's similar.

**Comment by strengejacke** [comment]
> it's similar.

Except that it's printed as HTML by default ;-)

> All the other functions like style_tt() and format_tt() should be possible for you.

Ok, haven't tried that yet, I think all my use cases were indeed to change the theme (which could then easily be passed to `print_html()`).

**Comment by strengejacke** [comment]
It seems that I get the same error with `style_tt()`:

```r
> print_html(out) |> style_tt(line_color = "green")
Error in attr(x, "tinytable_meta") <- meta_attr : 
  attempt to set an attribute on NULL
```

**Comment by strengejacke** [comment]
Here's a reprex:

``` r
library(tinytable)
x <- iris[1:3, 1:2]
out <- tt(x)
tab <- print(out, format = "html")
#> 
#> 
#> 
#> +--------------+-------------+
#> | Sepal.Length | Sepal.Width |
#> +==============+=============+
#> | 5.1          | 3.5         |
#> +--------------+-------------+
#> | 4.9          | 3           |
#> +--------------+-------------+
#> | 4.7          | 3.2         |
#> +--------------+-------------+
style_tt(tab, line_color = "green")
#> Error in attr(x, "tinytable_meta") <- meta_attr: attempt to set an attribute on NULL
```

<sup>Created on 2024-01-26 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
Ok, I have to revise some of the feedback I gave above - the markdown format actually is no problem. Today I had a totally messed up table, but maybe it was too wide for the console - I thought this was due to markdown format, but now it seems that this is obviously not the case - sorry for bashing the markdown-issue ;-)

**Comment by vincentarelbundock** [comment]
haha. But can you clarify the state of things now? What is the specific intended use that you cannot achieve currently?

**Comment by strengejacke** [comment]
Damn, typo in  my reprex, it should be `output = "html"`, but the error remains.

``` r
library(tinytable)
x <- iris[1:3, 1:2]
out <- tt(x)
tab <- print(out, output = "html")
#> 
#> <!DOCTYPE html> 
#> ...
#> 
#> </html>
style_tt(tab, line_color = "green")
#> Error in attr(x, "tinytable_meta") <- meta_attr: attempt to set an attribute on NULL
```

<sup>Created on 2024-01-26 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>


What I would like to have is comparable to `plot()` for, say, `parameters::model_parameters()`. It shows a ggplot-plot, because at the end of `plot()`, the ggplot-object is returned, which is plotted by default. Now, I can simply modify this plot, e.g. `plot() + ggplot2::scale_xyz()`. Replace `plot()` with a developers `print_html()` function, and `ggplot2::scale_xyz()` with a `tinytable` function.

``` r
library(tinytable)
a_developers_print_function <- function(x, ...) {
  out <- tt(x)
  print(out, output = "html")
}
x <- iris[1:3, 1:2]

# the default
a_developers_print_function(x)
#> 
#> <!DOCTYPE html> 
#> <html lang="en">
#> ...
#>   </body>
#> 
#> </html>

# if user wants to modify the output
a_developers_print_function(x) + style_tt(tab, line_color = "green")
#> 
#> <!DOCTYPE html> 
#> <html lang="en">
#> ...
#>     </script>
#> 
#>   </body>
#> 
#> </html>
#> Error in attr(x, "tinytable_meta") <- meta_attr: attempt to set an attribute on NULL
```

I want `a_developers_print_function(x) + style_tt(tab, line_color = "green")` working, like it did in version 0.0.1.

**Comment by vincentarelbundock** [comment]
Here's what I suggested above:

```r
library(tinytable)
print.custom_class <- function(x, ...) {
    tinytable:::print.tinytable(tab, output = "html")
}
tab <- tt(mtcars[1:4, 1:4]) 
class(tab) <- c("custom_class", class(tab))
print(tab)
```

This prints to HTML by default.

And your error is expected. Once you call `print()` on a `tinytable` object, it is fully instantiated, and it is no longer possible to modify it with the styling functions.

I'll try to raise a more informative error.

**Comment by strengejacke** [comment]
The custom class is not the problem.

This code worked perfect with tinytable 0.0.1:

```r
a_developers_print_function(x) |> style_tt(line_color = "green")
```

Now, the returned tinytable-object from my custom print function `a_developers_print_function()` no longer prints HTML by default, but markdown. Thus, although the user would expect a _HTML_ table, because my custom print function is named `print_html()`, returns markdown, and the user would need to do:

```r
my_custom_html_print_function(x) |>
  style_tt(line_color = "green") |>
  print(output = "html")
```

which really is awkward, or not?
It's like doing:

```r
gpplot(...) + scale_xy() |> plot()
```

why would I need an extra `plot()`?

The only way to avoid the additional `print(output = "html")` is if my `my_custom_html_print_function()` would directly print as HTML. But then, I cannot customize further.

It's like:

```r
my_plot <- function(x) {
  ggplot(x, ...) + geom_point()
}

my_plot() + geom_line() # error, you cannot add a layer after calling `my_plot()`
```

```

**Comment by strengejacke** [comment]
In other words, `a_developers_print_function(x) |> style_tt(line_color = "green")` only works for custom print methods that print to _markdown only_. If I have a custom print method that should print to _html_, all tinytable customization _has_ to be done inside my custom print function. But that somehow contradicts the design idea of "adding" functions, like `print() + style_tt() + format_tt()`.

That's why I _as developer_ need a way to make sure that if I return a tinytable object, I can force a certain output format (e.g. via `tt(output = "html")`, or maybe adding an attribute to the returned tinytable object or whatsoever.

Without this possibility, one of the major features (or even: requirements) for developers is gone.

**Comment by strengejacke** [comment]
I want to do something like this (not the blue cell colors, but _further modify my HTML(!) table_):

```r
library(gt)
a_developers_print_function <- function(x, ...) {
  insight::export_table(x, format = "html")
}

x <- iris[1:3, 1:2]

# the default
a_developers_print_function(x)
```
![image](https://github.com/vincentarelbundock/tinytable/assets/26301769/2f9998e3-019a-4821-8740-f818fed14f91)

```r
a_developers_print_function(x) |> 
  tab_style(
    style = cell_fill(color = "lightblue"),
    locations = cells_body()
  )
```
![image](https://github.com/vincentarelbundock/tinytable/assets/26301769/e21c971f-4d70-4375-ab47-12710f58bfcc)

**Comment by vincentarelbundock** [comment]
NEVER CALL `print()` BEFORE ONE OF THE STYLING FUNCTIONS.

That is *not* the intended design, and your previous code only worked by accident. If you try to apply `format_tt()` after `print()`, instead of `style_tt()` in version 0.0.1, it will break.

`print()` should always be the **very last call** in the chain.

I'm not sure it's that awkward. You only need to call `print()` manually if you don't like the default output. We can have an argument about `markdown` as default, but the concept of calling `print()` with an argument to change the default isn't weird or awkward in and of itself.

Here's an alternative strategy that does exactly what you want and does not rely on a weird print option:

```r
library(tinytable)

strenge_fun <- function() {
    out <- data.frame(a = 1:4)
    out <- tt(out)
    m <- attr(out, "tinytable_meta")
    m$output <- "html"
    attr(out, "tinytable_meta") <- m
    return(out)
}

strenge_fun() |> style_tt(color = "red") 
```

And I don't really think that your function should be called `print_html` anyway, since the beauty of the package is it can print to an appropriate output. For example, when the Quarto document is PDF, `tinytable` will use LaTeX.

**Comment by strengejacke** [comment]
> NEVER CALL print() BEFORE ONE OF THE STYLING FUNCTIONS.

That's exactly the point I was raising. I did not need to call `print()` in version 0.0.1, because the returned tinytable object was of course printed by default - to HTML(!). Now I no longer can produce beautiful HTML tables w/o calling `print()` _before_ the user possibly has done some further modifications, because now the default is printing to markdown - and I have no chance to change this (except calling `print()`).

> That is not the intended design

That is exactly your intended design, see the many examples in your vignettes:

![image](https://github.com/vincentarelbundock/tinytable/assets/26301769/12334901-7460-4022-b944-10337c8c05ed)

**Comment by strengejacke** [comment]
> Here's an alternative strategy that does exactly what you want and does not rely on a weird print option:

Yeah, that looks like the workaround I need now to make things again!

**Comment by vincentarelbundock** [comment]
What I mean by intended design is that the order matters and that `print()` should always be last.

Good:

```r
tt() |> style_tt() |> print()
```

Bad:

```r
tt() |> print() |> style_tt()
```

**Comment by strengejacke** [comment]
Yes, I know, but "good" no longer worked for HTML tables. That was my main issue I wanted to raise here, and I was looking for an option to make sure HTML will be the default format to print, so I can still have my "good" approach. Since version 0.0.2, I was suddenly forced to do "bad".

But if I can workaround this with

```r
    m <- attr(out, "tinytable_meta")
    m$output <- "html"
    attr(out, "tinytable_meta") <- m
```

I can be "good" again :-)
So finally, this issue can be closed (unless you want to make this workaround more obvious to other developers, too - or am I the only one using HTML format?)

**Comment by vincentarelbundock** [comment]
@strengejacke What I could do is export a `meta_tt()` function which is more developer focused and can be used to introspect and modify metadata about tables before printing.

**Comment by strengejacke** [comment]
Sounds good! Just curious, if `tinytables` automatically detects the context from which it's called and finds the appropriate format, when will HTML be chosen? There's RMarkdown (markdown), Markdown to PDF (Latex), interactive use (markdown) - so HTML will only be used when RMarkdown exports to an HTML page or vignette?

**Comment by vincentarelbundock** [comment]
Logic here: https://github.com/vincentarelbundock/tinytable/blob/main/R%2Fsanity.R

**Comment by vincentarelbundock** [comment]
This is now documented in the Details section.
