### ISSUE TITLE
[FR] Allow vector of column names in the `j` argument

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/tinytable#122]
Hi Vincent, I see that the `j` argument allows one to pass a vector of indices or a single character value but not a character vector:

``` r
library(tinytable)
options(tinytable_print_output = "html")

x <- data.frame(var1 = "aaa", var2 = "bbb", y = "ddd")

# Works
tt(x) |>
  style_tt(
    j = "var1|var2",
    background = "blue"
  )

# doesn't work: only styles first col
tt(x) |>
  style_tt(
    j = c("var1", "var2"),
    background = "blue"
  )
```

The last call prints the `grep()` warning about `length(pattern) > 1`. I know one can select several vars with a regex like in the first example so if I have a vector with column names, I could do `j = paste(my_vector, collapse = "|")`. However that's not very beginner-friendly and it's one additional step for the user. 

Could you automatically handle character vectors in the `j` argument? I hope that wasn't asked before, I didn't find any related issue

**Comment by etiennebacher** [comment]
I don't really understand the concern, single strings are already handled, right? I didn't read the code but I guess you could add something like:

```r
if (length(j) > 1 && is.character(j)) j = paste(j, collapse = "|")
```
and potentially use `paste(paste0("(", j, ")"), collapse = "|")` if you want to avoid `j = c("var1", "var2")` to capture `"var12"` as well

**Comment by vincentarelbundock** [comment]
Oh yeah, not problem with the coding. I'm saying if some wants to grab a single column called "age", they might also grab column "page" if we always treat a single string as a regex. That might be surprising, but we can document this.

**Comment by etiennebacher** [comment]
> if some wants to grab a single column called "age", they might also grab column "page" if we always treat a single string as a regex

I guess it makes more sense to treat strings as exact column names if length > 1. If people want to use several regexes then can combine them in a single string

**Comment by etiennebacher** [comment]
Actually it's probably not a great pattern to change the behaviour of `j` (regex or colnames) depending on its length. Ideally you would need a "marker" for being sure that the user passes a regex or not. Maybe if the string starts with `[reg]` then you consider it's a regex and otherwise an exact column name? Just throwing ideas here

**Comment by vincentarelbundock** [comment]
Maybe not the *best* pattern, but not a big deal either, I think. If documented well, it's fine.

Merged and live examples here: https://vincentarelbundock.github.io/tinytable/vignettes/tutorial.html#cells-rows-columns
