### ISSUE TITLE
Markdown: `style_tt()` cannot be applied to `group_tt()` row headers

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/tinytable#125]
See following examples, where HTML is correctly rendered, but in markdown, the wrong rows are recognized as "subheadings":

``` r
library(tinytable)
out <- data.frame(
  c172code = c(
    "low level of education", "intermediate level of education",
    "high level of education", "low level of education", "intermediate level of education",
    "high level of education"
  ),
  Predicted = c(
    "93.22", "96.07", "97.11",
    "85.73", "86.85", "84.50"
  ),
  CI = c(
    "86.89,  99.55", "91.15, 101.00",
    "90.86, 103.36", "79.67,  91.79", "81.16,  92.53", "78.07,  90.93"
  ),
  groups = c("low", "low", "low", "high", "high", "high")
)

# find start row of each subgroup
row_header_pos <- which(!duplicated(out$groups))
# create named list, required for tinytables
row_header_labels <- as.list(stats::setNames(row_header_pos, as.vector(out$groups[row_header_pos])))
# since we have the group names in "row_header_labels" now , we can remove the column
out$groups <- NULL
# make sure that the row header positions are correct - each header
# must be shifted by the number of rows above
for (i in 2:length(row_header_pos)) {
  row_header_pos[i] <- row_header_pos[i] + (i - 1)
}

out <- tinytable::tt(out)
# add subheaders, if any
if (!is.null(row_header_labels)) {
  out <- tinytable::group_tt(out, i = row_header_labels, indent = 2)
  out <- tinytable::style_tt(out, i = row_header_pos, italic = TRUE)
}

out
```

| c172code                          | Predicted | CI             |
|-----------------------------------|-----------|----------------|
| low                               |           |                |
| *low level of education*          | *93.22*   | *86.89, 99.55* |
| intermediate level of education   | 96.07     | 91.15, 101.00  |
| high level of education           | 97.11     | 90.86, 103.36  |
| high                              |           |                |
| low level of education            | 85.73     | 79.67, 91.79   |
| *intermediate level of education* | *86.85*   | *81.16, 92.53* |
| high level of education           | 84.50     | 78.07, 90.93   |

``` r

m <- attr(out, "tinytable_meta")
m$output <- "html"
attr(out, "tinytable_meta") <- m

print(out, output = "html")
```

**(HTML output not rendering here)**

<sup>Created on 2024-02-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
This is a known and documented problem, but it is not easy to solve because of package internal structure. 

Background (mostly for my own reference): markdown styling must occur before the table is "built", because each individual cell must be style individually. In contrast, HTML and LaTeX styling is applied *after* the table is built, because we can use CSS and friends instead of modifying individual cell content. This means that when we apply the styling in Markdown, `tinytable` doesn't have any information about the groups yet.

![Screenshot 2024-02-05 185741](https://github.com/vincentarelbundock/tinytable/assets/987057/9b903f46-66c1-4a33-bf65-f91e7571e785)

**Comment by vincentarelbundock** [comment]
I acknowledge this is a real problem, and I will keep thinking about it. Just to keep the repo clean, I'll consolidate all the "feature parity" for markdown here: https://github.com/vincentarelbundock/tinytable/issues/132

**Comment by strengejacke** [comment]
Thanks! I agree this is tricky. The indexing works different here, it seems that the inserted group rows are not recognized in later row indexing (argument `i`), see examples here:

``` r
library(tinytable)
out <- data.frame(
  c172code = c(
    "low level of education", "intermediate level of education",
    "high level of education", "low level of education", "intermediate level of education",
    "high level of education"
  ),
  Predicted = c(
    "93.22", "96.07", "97.11",
    "85.73", "86.85", "84.50"
  ),
  CI = c(
    "86.89,  99.55", "91.15, 101.00",
    "90.86, 103.36", "79.67,  91.79", "81.16,  92.53", "78.07,  90.93"
  ),
  groups = c("low", "low", "low", "high", "high", "high")
)

# find start row of each subgroup
row_header_pos <- which(!duplicated(out$groups))
# create named list, required for tinytables
row_header_labels <- as.list(stats::setNames(row_header_pos, as.vector(out$groups[row_header_pos])))
# since we have the group names in "row_header_labels" now , we can remove the column
out$groups <- NULL

out <- tinytable::tt(out)
out
```

| c172code                        | Predicted | CI            |
|---------------------------------|-----------|---------------|
| low level of education          | 93.22     | 86.89, 99.55  |
| intermediate level of education | 96.07     | 91.15, 101.00 |
| high level of education         | 97.11     | 90.86, 103.36 |
| low level of education          | 85.73     | 79.67, 91.79  |
| intermediate level of education | 86.85     | 81.16, 92.53  |
| high level of education         | 84.50     | 78.07, 90.93  |

``` r

out <- tinytable::group_tt(out, i = row_header_labels, indent = 2)
out
```

| c172code                        | Predicted | CI            |
|---------------------------------|-----------|---------------|
| low                             |           |               |
| low level of education          | 93.22     | 86.89, 99.55  |
| intermediate level of education | 96.07     | 91.15, 101.00 |
| high level of education         | 97.11     | 90.86, 103.36 |
| high                            |           |               |
| low level of education          | 85.73     | 79.67, 91.79  |
| intermediate level of education | 86.85     | 81.16, 92.53  |
| high level of education         | 84.50     | 78.07, 90.93  |

``` r

out <- tinytable::style_tt(out, i = row_header_pos, italic = TRUE)
out
```

| c172code                        | Predicted | CI             |
|---------------------------------|-----------|----------------|
| low                             |           |                |
| *low level of education*        | *93.22*   | *86.89, 99.55* |
| intermediate level of education | 96.07     | 91.15, 101.00  |
| high level of education         | 97.11     | 90.86, 103.36  |
| high                            |           |                |
| *low level of education*        | *85.73*   | *79.67, 91.79* |
| intermediate level of education | 86.85     | 81.16, 92.53   |
| high level of education         | 84.50     | 78.07, 90.93   |

``` r

out <- tinytable::style_tt(out, i = row_header_pos - 1, italic = TRUE)
out
```

| c172code                        | Predicted | CI              |
|---------------------------------|-----------|-----------------|
| low                             |           |                 |
| *low level of education*        | *93.22*   | *86.89, 99.55*  |
| intermediate level of education | 96.07     | 91.15, 101.00   |
| *high level of education*       | *97.11*   | *90.86, 103.36* |
| high                            |           |                 |
| *low level of education*        | *85.73*   | *79.67, 91.79*  |
| intermediate level of education | 86.85     | 81.16, 92.53    |
| high level of education         | 84.50     | 78.07, 90.93    |

<sup>Created on 2024-02-10 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
