### ISSUE TITLE
Dot align

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#135]

**Comment by sarahzeller** [comment]
This functionality would be great!

**Comment by sarahzeller** [comment]
Yay, looking forward to it!

**Comment by vincentarelbundock** [comment]
Notes to self.

Using the development version from Github, we can do:

```{r}
library(tinytable)
x <- data.frame(pi = c(pi * 100, pi * 1000, pi * 10000, pi * 100000))

dot <- "column{1}={si={table-format=6.5}}"

tt(x) |>
    format_tt(j = 1, digits = 8, num_fmt = "significant_cell") |>
    style_tt(tabularray_inner = dot)
```

In LaTeX, there are two challenges:

1. Pre-specifying the `table-format=6.5` argument, since that depends on the number of digits on either side of the dot. We could potentially compute a reasonable default by looking at `tab@table_dataframe`, but that's probably not 100% reliable.
2. `siunitx` settings in LaTeX get super complicated as soon as there are non-numeric characters, such as significance stars in a regression table.

In HTML, the challenge is that AFAICT, there is no standard way to do this, so we may need to split numbers and use weird spans.

In Typst, this may not be implemented at all.

In Markdown, this doesn't really make sense as a feature.

![Screenshot 2024-02-29 205309](https://github.com/vincentarelbundock/tinytable/assets/987057/6b74384c-d807-46e1-9ad8-b098ed8b0881)

**Comment by vincentarelbundock** [comment]
Now supported in the dev version on Github. Will be part of the next release. This is a LaTeX-only feature and is likely to remain so until Typst supports it out of the box. There is no "official" HTML strategy to do that, and all the hacks look... like hacks.
