### ISSUE TITLE
Row indices in format_tt()

### ISSUE THREAD

**Issue by Nenuial** [vincentarelbundock/tinytable#137]
Hi,
I have a table where I don't want the same number format in all rows.
The format_tt() function could allow me to change that, but it doesn't seem to offer the option to style only for certain rows.
Why is that?

**Comment by vincentarelbundock** [comment]
You are right: this should be supported.

The reason it is not right now is that it adds some code complexity. But i think it's worth it and I plan to do it when I find some free time.

**Comment by Nenuial** [comment]
Great news! Thanks for considering it.

**Comment by vincentarelbundock** [comment]
In the Github version, the `format_tt()` now accepts row indices:

``` r
library(tinytable)
x <- mtcars[1:4, 1:6]
tt(x) |> 
    format_tt(i = 1:2, j = c(5:6), num_fmt = "decimal", digits = 4) |>
    format_tt(i = 3:4, j = c(5:6), num_fmt = "decimal", digits = 2)
```

| mpg  | cyl | disp | hp  | drat   | wt     |
|------|-----|------|-----|--------|--------|
| 21.0 | 6   | 160  | 110 | 3.9000 | 2.6200 |
| 21.0 | 6   | 160  | 110 | 3.9000 | 2.8750 |
| 22.8 | 4   | 108  | 93  | 3.85   | 2.32   |
| 21.4 | 6   | 258  | 110 | 3.08   | 3.21   |
