### ISSUE TITLE
Allow setting significant digits by cell

### ISSUE THREAD

**Issue by avehtari** [vincentarelbundock/tinytable#142]
I've found tinytable to be very nice, but encountered couple issue. Here's the second one

Currently
```
> data.frame(x=c(0.000123456789, 12.4356789)) |> tt(digits=2)
+----------+
| x        |
+==========+
|  0.00012 |
+----------+
| 12.43568 |
+----------+
```
where the second row shows 7 significant digits instead of requested 2. I wish I could get formatting as
```
+----------+
| x        |
+==========+
|  0.00012 |
+----------+
| 12.      |
+----------+
```

**Comment by avehtari** [comment]
I would prefer seeing `# [1] "0.00012" "12"`, but even if the default would not change, I would be happy if there were an argument and possibly a global option, to get my preferred output. 

My use case is posterior summarise, e.g.
![image](https://github.com/vincentarelbundock/tinytable/assets/6705400/caa01230-d806-4d54-a914-a8631a6c095c)

Here we know that most of the time the default number of posterior draws gives us less than two significant digits accuracy, and thus extra digits are just noise and make it harder to read the table.  By default I would use `digits=2` and in the above table I sued `digits=1` just because there we too many digits already. The proposed behavior would be perfect for this use case.

A complete notebook in which I've tested using tinytable is https://avehtari.github.io/BDA_R_demos/demos_rstan/brms_demo.html

**Comment by kylebutts** [comment]
I think this is possible with `format_tt` and the `fn` argument. 

``` r
library(tinytable)
data.frame(x=c(0.000123456789, 12.4356789)) |> 
  format_tt(fn = \(x) signif(x, 2))
#>         x
#> 1 0.00012
#> 2      12
```

BTW, this might also be useful: https://search.r-project.org/CRAN/refmans/dreamerr/html/fsignif.html

**Comment by vincentarelbundock** [comment]
Thanks @kylebutts, this is a nice workaround.

@avehtari, I pushed three changes to make this easier:

1. `format_tt()` gains a new rounding style: `num_fmt="significant_cell"`
2. Numeric formatting arguments in `format_tt()` are now settable using global options.
3. Added an [example to the website tutorial.](https://vincentarelbundock.github.io/tinytable/vignettes/tutorial.html#significant-digits-and-decimals)

With Github `main`, you can now do:

``` r
library(tinytable)
k <- data.frame(x = c(0.000123456789, 12.4356789))

# column-wise significant
tt(k, digits = 2)
```

| x        |
|----------|
| 0.00012  |
| 12.43568 |

``` r

# cell-wise significant
tt(k) |> format_tt(digits = 2, num_fmt = "significant_cell")
```

| x       |
|---------|
| 0.00012 |
| 12      |

``` r

# cell-wise significant with global option
options("tinytable_format_num_fmt" = "significant_cell")
tt(k, digits = 2)
```

| x       |
|---------|
| 0.00012 |
| 12      |

**Comment by vincentarelbundock** [comment]
Closing now to cleanup the repo, but feel free to keep the conversation going if the current dev version does not meet your needs.

**Comment by avehtari** [comment]
Looks great! Two issues
- it seems the global option for the number of digits is now `options(digits = *)`, but would it be possible to have tinytable specific option for the digits?
- `options("tinytable_format_num_fmt" = "significant_cell")` seems to work only if the digits argument is used explicitly, that is, `* |> tt(digits=2)` uses `significant_cell`, but `* |> tt()` does not 

And one minor issue
- tidyverse global options seem to use dot `.` instead of underscore `_`. after the package name in the global options. Was it intentional to use underscore for tinytable options?

**Comment by vincentarelbundock** [comment]
@avehtari,

> it seems the global option for the number of digits is now options(digits = \*), but would it be possible to have tinytable specific option for the digits?

I added a global option to `tt()`.

> options(“tinytable_format_num_fmt” = “significant_cell”) seems to work only if the digits argument is used explicitly, that is, \* \|\> tt(digits=2) uses significant_cell, but \* \|\> tt() does not

I believe that the solution above solves this one too:

``` r
library(tinytable)
k <- data.frame(x = c(0.000123456789, 12.4356789))
options("tinytable_tt_digits" = 2)
options("tinytable_format_num_fmt" = "significant_cell")
tt(k)
```

| x       |
|---------|
| 0.00012 |
| 12      |

> tidyverse global options seem to use dot . instead of underscore \_. after the package name in the global options. Was it intentional to use underscore for tinytable options?

Yes, I personally dislike variable names and options with `.`, because they look too much like S3 methods. This is obviously an aesthetic preference, but I’m trying to be snake-case consistent across the package.

**Comment by avehtari** [comment]
Great! The global options now work, and most tables look good without additional options, and occasional `format_tt(num_fmt="decimal")` is sufficient. With this change, I'm definitely going to use tinytable more often

If you prefer, next time I can also test changes in PR before you merge to main

**Comment by vincentarelbundock** [comment]
Great news.

This is still a baby package, and I'm very eager to improve it, so don't hesitate to file other feature requests as you think of them.

And yes, for non-trivial features, we should definitely follow saner development procedures like testing in branch.
