### ISSUE TITLE
Add `fn` in `format_tt` to tutorial

### ISSUE THREAD

**Issue by kylebutts** [vincentarelbundock/tinytable#144]
Hi Vincent,

I am super excited about the custom function argument to `format_tt`. It fits into my current workflow really well. I was going to submit a PR with the below section for the tutorial, but figured an issue might be better.

The `r-lib/scales` package is really nice for common formatting (dates, currency, numbers, bytes, etc.), so I wanted to include an example using it in the tutorial, but the cost is adding the package to `suggests` in `DESCRIPTION`. Here's two versions of a section (one using scales and one that does not)

`````md
## Custom functions

On top of the built-in features of `format_tt`, a custom formatting function can be specified via the `fn` argument.

```{r}
x$mpg_rank = rank(-x$mpg, ties.method = "min")

tt(x) |> 
  format_tt(j = "mpg", fn = function(x) paste0(x, " mpg")) |>
  format_tt(j = "drat", fn = \(x) signif(x, 2)) |>
  # `scales` package has a lot of options (note label_* returns a function)
  format_tt(j = "mpg_rank", fn = scales::label_ordinal())

x$mpg_rank = NULL
```
`````

`````md
## Custom functions

On top of the built-in features of `format_tt`, a custom formatting function can be specified via the `fn` argument. The `fn` argument takes a function that accepts a single vector and returns a string (or something that coerces to a string like a number).  

```{r}
tt(x) |> 
  format_tt(j = "mpg", fn = function(x) paste0(x, " mpg")) |>
  format_tt(j = "drat", fn = \(x) signif(x, 2))
```

For example, the [`scales` package](https://scales.r-lib.org/index.html) which is used internally by `ggplot2` provides a bunch of useful tools for formatting (e.g. dates, numbers, percents, logs, currencies, etc.). The `label_*()` functions can be passed to the `fn` argument.
`````

**Comment by vincentarelbundock** [comment]
Oh yeah, this looks great. I'll definitely merge a PR if you put one together. Feel free to add any example you think might be useful to readers. Just make sure `scales` in is "Suggests" in DESCRIPTION so the website builds properly in the Github action.
