### ISSUE TITLE
`format_tt(escape = TRUE)` zaps previous formatting. From the vignette, that seems like unintended behavior?

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#147]
I think the last `format_tt(escape = TRUE)` zaps previous formatting. From the vignette, that seems like unintended behavior?

``` r
library(tinytable)

thumbdrives <- data.frame(
  date_lookup = as.Date(c("2024-01-15", "2024-01-18", "2024-01-14", "2024-01-16")),
  price = c(18.49, 19.99, 24.99, 24.99),
  price_rank = c(1, 2, 3, 3),
  memory = c(16e9, 12e9, 10e9, 8e9),
  speed_benchmark = c(0.6, 0.73, 0.82, 0.99)
)

tt(thumbdrives) |>
  format_tt(j = 1, fn = scales::label_date("%e %b", locale = "fr")) |>
  format_tt(j = 2, fn = scales::label_currency()) |>
  format_tt(j = 3, fn = scales::label_ordinal()) |> 
  format_tt(j = 4, fn = scales::label_bytes()) |> 
  format_tt(j = 5, fn = scales::label_percent())
```

| date_lookup | price   | price_rank | memory | speed_benchmark |
|-------------|---------|------------|--------|-----------------|
| 15 janv.    | \$18.49 | 1st        | 16 GB  | 60%             |
| 18 janv.    | \$19.99 | 2nd        | 12 GB  | 73%             |
| 14 janv.    | \$24.99 | 3rd        | 10 GB  | 82%             |
| 16 janv.    | \$24.99 | 3rd        | 8 GB   | 99%             |

``` r

tt(thumbdrives) |>
  format_tt(j = 1, fn = scales::label_date("%e %b", locale = "fr")) |>
  format_tt(j = 2, fn = scales::label_currency()) |>
  format_tt(j = 3, fn = scales::label_ordinal()) |> 
  format_tt(j = 4, fn = scales::label_bytes()) |> 
  format_tt(j = 5, fn = scales::label_percent()) |>
  format_tt(escape = TRUE)
```

| date_lookup | price | price_rank | memory | speed_benchmark |
|-------------|-------|------------|--------|-----------------|
| 2024-01-15  | 18.49 | 1st        | 16 GB  | 0.60            |
| 2024-01-18  | 19.99 | 2nd        | 12 GB  | 0.73            |
| 2024-01-14  | 24.99 | 3rd        | 10 GB  | 0.82            |
| 2024-01-16  | 24.99 | 3rd        | 8 GB   | 0.99            |

<sup>Created on 2024-02-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

_Originally posted by @kylebutts in https://github.com/vincentarelbundock/tinytable/issues/146#issuecomment-1957228052_

**Comment by kylebutts** [comment]
Actually, it seems to have nothing to do with custom function. `format_tt` operates on the original value and does not "chain":

``` r
library(tinytable)
tt(mtcars[1:3, ]) |>
  format_tt(j = "mpg", num_mark_dec = "$") |>
  format_tt(j = "mpg", escape = TRUE) 
```

| mpg  | cyl | disp | hp  | drat | wt    | qsec  | vs  | am  | gear | carb |
|------|-----|------|-----|------|-------|-------|-----|-----|------|------|
| 21.0 | 6   | 160  | 110 | 3.90 | 2.620 | 16.46 | 0   | 1   | 4    | 4    |
| 21.0 | 6   | 160  | 110 | 3.90 | 2.875 | 17.02 | 0   | 1   | 4    | 4    |
| 22.8 | 4   | 108  | 93  | 3.85 | 2.320 | 18.61 | 1   | 1   | 4    | 1    |

<sup>Created on 2024-02-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
Thanks a lot for the investigation @kylebutts. I’m hoping the most recent commit fixes this:

``` r
library(tinytable)
x <- data.frame(num = c(pi, pi), char = c("10$", "blah_blah"))

# overwrite
tt(x) |>
  format_tt(i = 1, j = 1, digits = 2) |>
  format_tt(i = 1, j = 1, digits = 3)
```

| num      | char       |
| -------- | ---------- |
| 3.14     | 10$        |
| 3.141593 | blah\_blah |

``` r

# different cells
tt(x) |>
  format_tt(i = 1, j = 1, digits = 2) |>
  format_tt(i = 2, j = 1, digits = 3) 
```

| num  | char       |
| ---- | ---------- |
| 3.1  | 10$        |
| 3.14 | blah\_blah |

``` r

# do not zap, but escape
tt(x) |>
  format_tt(i = 1, j = 1, digits = 2) |>
  format_tt(i = 2, j = 1, digits = 3) |>
  format_tt(escape = TRUE) |> 
  print("latex")
# 
# \begin{table}
# \centering
# \begin{tblr}[         %% tabularray outer open
# ]                     %% tabularray outer close
# {                     %% tabularray inner open
# colspec={Q[]Q[]},
# }                     %% tabularray inner close
# \toprule
# num & char \\ \midrule %% TinyTableHeader
# 3.1 & 10\$ \\
# 3.14 & blah\_blah \\
# \bottomrule
# \end{tblr}
# \end{table}
```

**Comment by kylebutts** [comment]
Hmm, my example is still not working https://github.com/vincentarelbundock/tinytable/issues/147#issuecomment-1957332526

What's the intended behavior of using `format_tt()` on the same cell twice? Apply the second onto the result of the first? Or apply just the second? Old commits did the former; new commits do the latter

**Comment by vincentarelbundock** [comment]
No, I think the intended behavior is to have it be completely overwritten by the second call. 

Imagine you first call format_tt(digits=2), and then call format_tt(digits=4)

The second call is not possible because we've destroyed information above the trailing digits and we have a strong. There's no simple way to figure out what formatting options can be combined sequentially.

escape is kind of an exception, because it's just some regexes that we apply to strings at the end.

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/tinytable/commit/7c7d28777fbf81bd0176eb68b010369ed6b23702

Docs clarification

**Comment by vincentarelbundock** [comment]
Documented as a breaking change here: da2c505b5010a6a9c51ff0755eab2ae700bead4c
