### ISSUE TITLE
Typst: support `plot_tt()`

### ISSUE THREAD

**Issue by aghaynes** [vincentarelbundock/tinytable#151]
I just came across your package while playing with the typst  format that quarto has just included. Seems to be best for typst tables i've come across... :)

I tried out some of your examples... the ones with the embedded figures dont work though :( The following line stops it... 
https://github.com/vincentarelbundock/tinytable/blob/53ef9b2b26f27c10e04b2c16a41979c31c17343a/R/plot_tt.R#L205

Any chance you'll add support for that?

**Comment by aghaynes** [comment]
this example from the "spanning cells" section doesnt work properly either
```
tt(x)|> style_tt(
  i = 2, j = 2,
  colspan = 3,
  rowspan = 2,
  align = "c",
  alignv = "m",
  color = "white",
  background = "black",
  bold = TRUE)
```

**Comment by vincentarelbundock** [comment]
Yes, thanks, I definitely do want to support this. I just need to find some time to implement it.

**Comment by aghaynes** [comment]
i think i've managed to do this... will make a PR shortly :)

**Comment by vincentarelbundock** [comment]
Oh wow, that's awesome!
