### ISSUE TITLE
Typst: multipage

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#154]
+ [x] LaTeX
+ [ ] Typst

@aghaynes, yes, I would like to support this. Do you know what the syntax is for multi-page tables in Typst? I use the `tablex` extension package if that matters.

Multi-page tables in LaTeX will be supported via `longtblr` in Tabularray. See: https://github.com/vincentarelbundock/tinytable/issues/13

**Comment by aghaynes** [comment]
I've only just started looking at typst today to be honest... (although I'm hoping that my group can start using it as an alternative to latex - it seems much quicker and seems to have fewer technical difficulties)

https://github.com/PgBiel/typst-tablex?tab=readme-ov-file#repeat-header-rows

Looks like `repeat-header: true` is enough as you're already using `tablex`...

**Comment by aghaynes** [comment]
i've figured out the issue (by manually editing the typ file and rendering that)... 

 - the nesting of the table within block seems to stop the repeating headers and 
 - nesting the table within figure is whats stopping the breaking (presumably typst doesnt like a single figure to be on more than 1 page... which makes sense)

So lines 6 and 24 here would need commenting out/removing https://github.com/vincentarelbundock/tinytable/blob/main/inst/templates/typst.typ  and whatever is causing the block should be amended too (it looks to me as if this is a pandoc thing, as the block isn't present in the typst.md file)

**Comment by vincentarelbundock** [comment]
Ah, good to know, thanks for the investigation.

Instead of doing a lot of commenting-out and adding new lines, we could have a new `.typ` file in the `templates` folder, and select that if the user calls `tt(x, theme = "longtable")`. This is what we do in LaTeX for different themes, where instead of modifying the code, we just load up a new template: https://github.com/vincentarelbundock/tinytable/tree/main/inst/templates

Eventually, what I'd like to do is allow users to supply their own templates in that argument, which would allow super deep customization very easily.

**Comment by aghaynes** [comment]
sounds good. 
was there a reason you added wrapped everything in figure? (i'm very new to typst, so maybe there's something subtle that i've not yet discovered)

**Comment by vincentarelbundock** [comment]
I am also very new to Typst, so I'm not actually sure this is the best choice. But I wanted to be consistent with LaTeX, where I wrap everything in a floating `table` environment.

I do want to add a "theme" for raw tabular, without the float, and that could apply to Typst as well.

**Comment by aghaynes** [comment]
lots of changes for tables coming to typst soon... https://staging.typst.app/docs/changelog

**Comment by vincentarelbundock** [comment]
Note to self:

PR https://github.com/vincentarelbundock/tinytable/pull/240 implements multipage figures automatically, but this requires a special raw Typst block in Quarto, because Quarto automatically wraps tables in a non-breakable figure environment.

Example:

````
---
format:
    typst:
        keep-typ: true
---

```{=typst}
#show figure: set block(breakable: true)
```

```{r}
#| tbl-cap: "blah blah blah"
#| label: tbl-blah
#| echo: false
#| message: false
library(tinytable)
tt(head(iris, 50)) |>
    group_tt(j = list(Hello = 1:2, World = 3:4))
```
````

**Comment by vincentarelbundock** [comment]
Added the above info to the FAQ. Closing this issue now in anticipation of the merging of the PR.
