### ISSUE TITLE
Typst features

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#17]
+ [ ] `notes` argument in `tt()`
+ [ ] `width` both in `style_tt()` and `tt()`
+ [ ] `rowspan` in `style_tt()`
+ [ ] `colspan` in `style_tt()`
+ [ ] `alignv` argument in `style_tt()`
+ [x] `align` argument in `style_tt()`: `d` for decimal alignment is not supported by Typst, AFAICT.
+ [x] `format_tt(escape)` should escape `<` characters. For example, Typst compilation breaks with "p<0.001". MWE below.
+ [x] `group_tt()` with row groups (column groups already supported).

I think that everything else is supported, but would love some user feedback.

**Comment by petermacp** [comment]
`tinytable` looks amazing - thanks! 

I have recently been experimenting with Typst, and looks like `tinytable` could solve lots of problems related to rendering tables with Typst.

Appreciate this is early days, so apologies if rushing you too much. With this workflow, I am struggling to render a `tinytable`.

1. Open new .qmd file
2. Render code below to .pdf output
3. Results shown in image attached.

---
title: "Test table"
format: typst
---


```{r}

library(tinytable)

mtcars |> tt()

```

Very grateful if you have any suggestions about how to get started with this.

Thanks!

<img width="855" alt="Screenshot 2024-01-15 at 10 46 14" src="https://github.com/vincentarelbundock/tinytable/assets/13797996/e1302ba6-08a3-440d-93e9-f479b20e2c4b">

**Comment by vincentarelbundock** [comment]
Sorry @petermacp I think I jumped the gun in the README. Typst support is on the roadmap, but not implemented yet.

That said, I should say that I use Typst all the time myself, and that I already have working code for very basic tables. So it shouldn't take very long before this is in.

I'll ping you once the feature is available.

Sorry for the misleading ads...

**Comment by petermacp** [comment]
Sounds amazing! Fantastic work, and thanks again!

**Comment by vincentarelbundock** [comment]
Note to self: it should be possible to replicate many `tinytable` features pretty easily using `tablex` for `Typst`. Example:

![typst](https://github.com/vincentarelbundock/tinytable/assets/987057/1e94771e-dcb8-4749-8b2f-18b5bbd2b4d2)

```typst

#import "@preview/tablex:0.0.8": tablex, hlinex, vlinex
#let nrows = 6;
#let nhead = 1;

#tablex(
  columns: 4,
  align: left + horizon,
  auto-lines: false,
  header-rows: 1,

  // lines
  hlinex(y: 0, stroke: black + .1em),
  hlinex(y: nhead, stroke: black + .05em),
  hlinex(y: nrows, stroke: black + .1em),
  hlinex(y: 6, stroke: black + .1em),
  hlinex(start: 0, end: 3, y: 4, stroke: rgb("#239dad") + .2em),
  vlinex(x: 2, stroke: yellow + .5em),

  map-cells: cell => {

    // align
    let j = (1,);
    if (j.contains(cell.x)) { cell.align = center };

    // background
    let i = (2,4);
    let j = (1,);
    if (i.contains(cell.y) and j.contains(cell.x)) { cell.fill = olive };

    // color
    let i = (2,4);
    let j = (1,);
    if (i.contains(cell.y) and j.contains(cell.x)) { cell.content = { set text(white); cell.content } }

    // italic
    let i = (0,);
    if (i.contains(cell.y)) { cell.content = { emph(cell.content) } }

    // underline
    let i = (3,4,);
    let j = (3,);
    if (i.contains(cell.y) and j.contains(cell.x)) { cell.content = { underline(cell.content) } }

    // underline
    let i = (3,4,);
    let j = (3,);
    if (i.contains(cell.y) and j.contains(cell.x)) { cell.content = { strike(cell.content) } }

    // bold
    let i = (1,);
    if (i.contains(cell.y)) { cell.content = { strong(cell.content) } }



    return cell;


  },


  [Username], [Location], [Height], [Score],
  [John], [Second St.], [180 cm], [5],
  [Wally], [Third Av.], [160 cm], [10],
  [Jason], [Some St.], [150 cm], [15],
  [Robert], [123 Av.], [190 cm], [20],
  [Other], [Unknown St.], [170 cm], [25],
)
```

**Comment by vincentarelbundock** [comment]
@petermacp most of Typst support is implemented and available on Github, except for a couple minor exceptions listed in the first post. Let me know if you get a chance to try it out.

I'm pretty excited about this!

Screenshot and Quarto document below.

![typst](https://github.com/vincentarelbundock/tinytable/assets/987057/1bf37a18-a11c-4bfb-aeb8-f164b09ab8e8)

Quarto document:

````markdown
---
format:
    typst:
        keep-typ: true
---


```{r}
library(tinytable)
mtcars[1:4, 1:5] |>
    tt(caption = "Hello World") |>
    group_tt(j = list("Group 1" = 4:5, "Group 2" = 2:3)) |>
    style_tt(j = 1:5, align = "lcccr") |>
    style_tt(i = 2, j = 1:3, background = "black", color = "white") |>
    style_tt(j = 1, color = "red", italic = TRUE, strikeout = TRUE)
```
````

**Comment by petermacp** [comment]
Wow! That looks amazing! Just installed the GitHub version to try, but having a bit of difficulty in rendering, with the following error:

```
==> quarto preview test.qmd --to typst --no-watch-inputs --no-browse



processing file: test.qmd
  |....................................................| 100% [unnamed-chunk-1]


Quitting from lines 9-16 [unnamed-chunk-1] (test.qmd)
Error in `dev.control()`:
! dev.control() called without an open graphics device
Backtrace:
  1. global .main()
  2. execute(...)
  3. rmarkdown::render(...)
  4. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  5. knitr:::process_file(text, output)
     ...
 11. knitr:::call_block(x)
 12. knitr:::block_exec(params)
 13. knitr:::eng_r(options)
 14. knitr:::chunk_device(options, keep != "none", tmp.fig)
 15. grDevices::dev.control(displaylist = if (record) "enable" else "inhibit")
Warning messages:
                                                                                                            In grSoftVersion() :
  unable to load shared object '/Library/Frameworks/R.framework/Resources/modules//R_X11.so':
  dlopen(/Library/Frameworks/R.framework/Resources/modules//R_X11.so, 0x0006): Library not loaded: /opt/X11/lib/libSM.6.dylib
  Referenced from: <A6A60F0C-DFA1-3218-B816-7CAADC1A4CD5> /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/modules/R_X11.so
  Reason: tried: '/opt/X11/lib/libSM.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/X11/lib/libSM.6.dylib' (no such file), '/opt/X11/lib/libSM.6.dylib' (no such file), '/Library/Frameworks/R.framework/Resources/lib/libSM.6.dylib' (no such file), '/Library/Java/JavaVirtualMachines/jdk-17.0.1+12/Contents/Home/lib/server/libSM.6.dylib' (no such file)
2: In cairoVersion() :
  unable to load shared object '/Library/Frameworks/R.framework/Resources/library/grDevices/libs//cairo.so':
  dlopen(/Library/Frameworks/R.framework/Resources/library/grDevices/libs//cairo.so, 0x0006): Library not loaded: /opt/X11/lib/libXrender.1.dylib
  Referenced from: <4E98F252-F967-3470-9CCF-B81DCB7D3429> /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/grDevices/libs/cairo.so
  Reason: tried: '/opt/X11/lib/libXrender.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/X11/lib/libXrender.1.dylib' (no such file), '/opt/X11/lib/libXrender.1.dylib' (no such file), '/Library/Frameworks/R.framework/Resources/lib/libXrender.1.dylib' (no such file), '/Library/Java/JavaVirtualMachines/jdk-17.0.1+12/Contents/Home/lib/server/libXrender.1.dylib' (no such file)
3: In (function (filename = if (onefile) "Rplots.svg" else "Rplot%03d.svg",  :
  failed to load cairo DLL

Execution halted
```

**Comment by vincentarelbundock** [comment]
Weird. I don't get the same error, and that looks like something specific to your machine (cairo, etc).

Can you try to just `render` the file instead of `preview`?

```sh
quarto render test.qmd --to typst
```

**Comment by petermacp** [comment]
Thanks so much - got this to work by reinstalling XQuartz on my Mac, so clearly a system error, not a `tinytable` error!

Will start working on my real document now, and let you know if I hit any other issues.

Thanks so much again!

**Comment by vincentarelbundock** [comment]
Yay!

**Comment by vincentarelbundock** [comment]
Thanks a lot for trying it out and reporting back. I appreciate it!

I added `width` to the list. Good catch.

I'm not sure specifying the font should be in scope for a table drawing package. This is something that should be easy to control in the document itself, and we typically want the table font to match the document font, no?

**Comment by petermacp** [comment]
Thanks!

Re: Fonts. Maybe I am missing something, but my tables seem to be rendered in the .pdf with a different font to the rest of the document. 

e.g., With this code, the table font doesn't match the document body text.

```
---
title: ""
format: 
  typst:
    keep-typ: true
    mainfont: "Source Sans Pro"
---

```{=typst}

// Overall set-up
#set page(
    numbering: "1", 
    number-align: start,
    margin: (x: 50pt, y: 40pt),
)

#set text(
  font: "Source Sans Pro",
  size: 11pt
)

```

```{=typst}

// My name
#let name = [Peter *MacPherson*]
#let title = [An example document]

#align(left, text(18pt, rgb("#01497c"))[
  *#name*
])

#v(10pt, weak: true)

#align(left, text(12pt, rgb("#01497c"), weight: "light")[
  *#title*
])

#v(4pt, weak: true)


```

```{=typst}


#v(25pt, weak: true)

#align(left, text(10pt, rgb("#212529"), weight: "light")[
  Here is some text. in Source Sans Pro, size 10pt
])

#v(25pt, weak: true)

```

```{r}
library(tinytable)
mtcars[1:4, 1:5] |>
    tt(caption = "A table")
```
```

<img width="948" alt="Screenshot 2024-01-30 at 08 35 36" src="https://github.com/vincentarelbundock/tinytable/assets/13797996/8f08efab-6890-4818-8bb9-5bfe432e7eff">

**Comment by vincentarelbundock** [comment]
Is this a quarto-specific thing? What happens if you save the table and compile.the file with typst directly from a .typ file?

**Comment by vincentarelbundock** [comment]
So here's a screenshot of what I get when i compile the Typst document below. The table was produced by `tinytable` and saved to a `.typ` file using `save_tt()`. Then, I added some text for comparison. To my eye, both look like Linux Libertine, which is the default typeface in Typst. 

So my conclusion is that Quarto must be overriding the default font choice in Typst, but fails to apply the same font in raw typst blocks (with the `=typst` decoration).

I think this is a Quarto inconsistency and not a problem which can be solved in `tinytable`. A workaround would be to call a Typst command in the Quarto document to set the rest of the document to the same font as the table.

![typeface](https://github.com/vincentarelbundock/tinytable/assets/987057/dbff7f7e-64ce-47b1-9d5c-b58e6f4dc4de)

````typst
The quick brown fox jumps over the lazy dog.

#import "@preview/tablex:0.0.8": tablex, hlinex, vlinex, colspanx
#let nhead = 1;
#let nrow = 1;
#let ncol = 1;

#figure(
  
  tablex(
    columns: ncol,
    header-rows: nhead,
    align: left + horizon,
    auto-lines: false,

hlinex(y: 0, start: 0, end: 1, stroke: 0.1em + black),
hlinex(y: 1, start: 0, end: 1, stroke: 0.05em + black),
hlinex(y: 2, start: 0, end: 1, stroke: 0.1em + black),
    // tinytable lines before

    map-cells: cell => {



      // tinytable cell style before
      return cell;
    },

    // tinytable cell content after
[sentence],
[The quick brown fox jumps over the lazy dog.]


  ) // end tablex
) // end figure
````

**Comment by petermacp** [comment]
Thanks! Yes, having done a bit of reading around, I agree that this is what is happening. Thanks so much for looking into this.

**Comment by vincentarelbundock** [comment]
```r
library(marginaleffects)
dat <- read.csv("https://vincentarelbundock.github.io/Rdatasets/csv/palmerpenguins/penguins.csv")
dat$large_penguin <- ifelse(dat$body_mass_g > median(dat$body_mass_g, na.rm = TRUE), 1, 0)

mod <- glm(large_penguin ~ bill_length_mm + flipper_length_mm + species,
           data = dat, family = binomial)

print(avg_slopes(mod), style = "tinytable", digits = 2)
```

**Comment by aghaynes** [comment]
> ```r
> library(marginaleffects)
> dat <- read.csv("https://vincentarelbundock.github.io/Rdatasets/csv/palmerpenguins/penguins.csv")
> dat$large_penguin <- ifelse(dat$body_mass_g > median(dat$body_mass_g, na.rm = TRUE), 1, 0)
> 
> mod <- glm(large_penguin ~ bill_length_mm + flipper_length_mm + species,
>            data = dat, family = binomial)
> 
> print(avg_slopes(mod), style = "tinytable", digits = 2)
> ```

or a tt.slopes method... `avg_slopes(mod) |> tt()` (although I'm not sure whether tt is already a generic or not)

**Comment by vincentarelbundock** [comment]
`tt` is not a generic, and in general I think that `tinytable` should be a "basic" package, and not provide methods for a ton of other packages. FWIW, i've already implemented support for `tinytable` in the dev version of `marginaleffects`, so this should work: `print(avg_slopes(model), "tinytable")`

**Comment by aghaynes** [comment]
you wouldn't necessarily have to have the support for loads of tt methods in tinytable - do it like broom: tt methods in the relevant packages. Was just an idea when i saw your comment :)

**Comment by vincentarelbundock** [comment]
Yeah, that makes sense. 

In case you didn't know, I'm also the maintainer [of the `modelsummary` package](https://modelsummary.com), and I am currently working on version 2.0.0 which will use `tinytable` as table-drawing package instead of `kableExtra`. `modelsummary` will then be much lighter, and it already has a ton of features to summarize pretty much any fitted model object you throw at it.

**Comment by henrikkarlstrom** [comment]
This package works beautifully! Would it be possible to make it add a "kind: " field to the typst table output, so it can be targeted by a show rule? I would like to make a List of tables, and a generic "kind: tt_table" or something similar in the table body would allow me to generate this with outline(target: figure.where(kind: "tt_table")).

**Comment by vincentarelbundock** [comment]
Got it. 

Commit b5876d0567ca0a4597710e7c70bec3bc284a5a9b adds `kind: tinytable,` to every Typst table generated by `tinytable`.

I'd love it if you could install the dev version from Github and let me know if it works as intended for you.

**Comment by vincentarelbundock** [comment]
Issue broken in separate issues
