### ISSUE TITLE
Typst: kind parameter

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#170]
> Would it be possible to make it add a "kind: " field to the typst table output

_Originally posted by @henrikkarlstrom in https://github.com/vincentarelbundock/tinytable/issues/17#issuecomment-1976535511_
            
Glad you like the package @henrikkarlstrom!

To customize LaTeX tables, there are `tabularray_inner` and `tabularray_outer` arguments in `style_tt()`. These will insert arbitrary strings in two different locations of the table, allowing users to set custom `tabularray` options.

I could implement a similar thing for Typst tables, allowing you to customize whatever you want about the table by inserting code in specific locations.

I admit that I'm not a Typst expert, so I could use your help here. Where would it make sense to insert arbitrary user-supplied code --- like your proposed "kind" --- in this table?

```typst
#import "@preview/tablex:0.0.8": tablex, hlinex, vlinex, colspanx
#let nhead = 1;
#let nrow = 3;
#let ncol = 4;
#figure(
  tablex(
    columns: ncol,
    header-rows: nhead,
    align: left + horizon,
    auto-lines: false,

hlinex(y: 0, start: 0, end: 4, stroke: 0.1em + black),
hlinex(y: 1, start: 0, end: 4, stroke: 0.05em + black),
hlinex(y: 4, start: 0, end: 4, stroke: 0.1em + black),
    // tinytable lines before

    map-cells: cell => {
      // tinytable cell style before
      return cell;
    },

    // tinytable cell content after
[mpg], [cyl], [disp], [hp],
[21.0], [6], [160], [110],
[21.0], [6], [160], [110],
[22.8], [4], [108], [ 93],

  ) // end tablex
) // end figure 
```

**Comment by vincentarelbundock** [comment]
Aaah, I see. You think I should insert this to ALL typst tables generated by the package. Correct?

**Comment by vincentarelbundock** [comment]
Got it.

Commit https://github.com/vincentarelbundock/tinytable/commit/b5876d0567ca0a4597710e7c70bec3bc284a5a9b adds kind: "tinytable", to every Typst table generated by tinytable.

I'd love it if you could install the dev version from Github and let me know if it works as intended for you.

**Comment by henrikkarlstrom** [comment]
Works like a charm! Thank you for the extremely quick response

**Comment by vincentarelbundock** [comment]
@henrikkarlstrom it was strongly suggested to me by the Quarto developers that `tinytable` should not insert a `kind` parameter or a `figure` environment in Quarto in the special case where `tbl-cap` or `label` chunk options are defined. Quarto inserts its own `kind`.

This is just a heads up that the next release will ahve a breaking change if you use Quarto + Typst.

**Comment by henrikkarlstrom** [comment]
Thanks for the heads up! It seems they've changed the way they insert the kind-parameter with the new updates to tables in Typst, so maybe it is now possible to target the Quarto-built tables with Typst styling templates directly. Ah, the joys of working with software still in development...
