### ISSUE TITLE
Typst: bootstrap theme

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#187]

**Comment by marcboschmatas** [comment]
Hi, I'd like to give a hand with this issue, but I don't really know where to start, I'm not sure I get how the code is organised. If you could point me a bit in the right direction it would be really helpful.

**Comment by vincentarelbundock** [comment]
Thanks, this would be fantastic!

The key step would be to modify the `theme_void()` and `theme_bootstrap()` functions in this file:

https://github.com/vincentarelbundock/tinytable/blob/main/R/theme_tt.R

If you look at the `theme_default()` and `theme_tabular()` functions in that same file, you'll see that the process is very straightforward.

There are some utility functions that can make your life easier to drop code or add lines in specific sections of the Typst code. Look for [the `typst_insert()` function](https://github.com/vincentarelbundock/tinytable/blob/main/R/tt_typst.R#L24) and all [the `lines_*()` functions in this file.](https://github.com/vincentarelbundock/tinytable/blob/main/R/utils.R#L18)

If everything goes well, you should be able to do this and get what you want:

```r
tt(x) |> theme_tt("void")
```

And if we are lucky, this will also work automatically as soon as your `theme_void()` is properly modified:

```r
tt(x, theme = "void")
```

Finally, note that some operations need to be conducted at very specific points in table building. I would really like to avoid this at all costs, and stick with `theme_*()` functions. But this is why there are some themeing operations in `R/tt_tabularray.R` and `R/tt_bootstrap.R`. This is just a heads up that this exists, but we want to avoid this if possible for Typst.

Thanks for taking a look!

**Comment by marcboschmatas** [comment]
Brilliant! I'll take a look

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/tinytable/pull/240
