### ISSUE TITLE
Use repeated colnames

### ISSUE THREAD

**Issue by MarcoPortmann** [vincentarelbundock/tinytable#194]
I think in combination with group headers it is common to have repeated colnames. What I want to achieve is "a" header a with subheader sub1 & sub2 and a header "b" with sub1 & sub2.  Howver, I don't see a way to feed them into tinytable.  `dplyr::rename` does not allow duplicates and, as far as I know, `tt` doesn't have an argument to set colnames.

```r
 tibble(a_sub1 = 1, a_sub2 =2, b_sub1 = 3, b_sub2 = 4) %>% 
   tt() %>% 
   group_tt(j = list(a = 1:2, b = 3:4))
````

**Comment by vincentarelbundock** [comment]
Sorry, I don't understand what you mean. Could explain differently and ideally show me an example of a table like the one you want?

**Comment by MarcoPortmann** [comment]
I'd like to achieve an output like this:
```r
tibble(a_sub1 = 1, a_sub2 =2, b_sub1 = 3, b_sub2 = 4) %>% 
  rename(sub1 = "a_sub1", sub2 = "a_sub2", "sub1 " = "b_sub1", "sub2 " = "b_sub2")  %>% 
  tt() %>% 
  group_tt(j = list(a = 1:2, b = 3:4))
```

![image](https://github.com/vincentarelbundock/tinytable/assets/7468121/5280ebaa-3f3e-4fba-a562-29eee1e32b66)

Howver, it would be nice to achieve it without the workaround of extra spaces in  "sub1 " and "sub2 " which are required since a tibble cannot have two columns with identical colnames.

**Comment by vincentarelbundock** [comment]
`tinytable` already supports duplicated column names without any problem:

``` r
library(tinytable)
data.frame(sub1 = 1, sub2 = 2, sub1 = 3, sub2 = 4, check.names = FALSE) |>
    tt() |>
    group_tt(j = list(a = 1:2, b = 3:4))
```

| a    |      | b    |      |
|------|------|------|------|
| sub1 | sub2 | sub1 | sub2 |
| 1    | 2    | 3    | 4    |

I’m closing this because this is not a limitation of `tinytable`, but rather a feature request for `tibble()` to allow duplicated column names.

**Comment by vincentarelbundock** [comment]
Actually, it looks like `tibble` *does* in fact support repeated names, and has a specific argument for it:

```r
tibble(sub1 = 1, sub2 = 2, sub1 = 3, sub2 = 4, .name_repair = "minimal") |>
    tt() |>
    group_tt(j = list(a = 1:2, b = 3:4))
```

**Comment by MarcoPortmann** [comment]
You're right. Interesting. It seems that `.name_repair = "minimal"` can be provided to `tibble`but not to other functions like `rename`.
