### ISSUE TITLE
Missing or unexported object: ‘tinytable::theme_tt’ for mac os x?

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/tinytable#197]
See:
https://cran.r-project.org/web/checks/check_results_insight.html
https://www.r-project.org/nosvn/R.check/r-oldrel-macos-arm64/insight-00check.html

Is it because _tinytable_ fails on CRAN for that OS?

**Comment by vincentarelbundock** [comment]
Maybe the macos.binaries has not been built yet when these tests were run?

**Comment by strengejacke** [comment]
Not sure, but _tinytable_ tests fail on CRAN for mac os: https://cran.r-project.org/web/checks/check_results_tinytable.html

**Comment by vincentarelbundock** [comment]
I'm quite convinced this is because it was a really new exported function, and that the mac binaries had not been built yet. 

The other problem is complete separate and fixed here: f349b5fc

**Comment by strengejacke** [comment]
Thanks! I _think_ this issue prevented building binaries on CRAN, because CRAN only builds binaries when checks pass.

**Comment by vincentarelbundock** [comment]
Interesting. I guess.theyll order me to submit a new version soon...
