### ISSUE TITLE
tinytable on conda ?

### ISSUE THREAD

**Issue by JulieBlasquiz** [vincentarelbundock/tinytable#211]
Hi !

Thanks for this amazing package ! 

It would be a plus to make installation possible via conda

Many thanks

Julie

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion. 

I have never used conda and don't know much about it.

Could you give me more information about how packages get selected to be built there? I notice that some of my other packages like marginaleffects and modelsummary are there, without me doing anything special.

**Comment by JulieBlasquiz** [comment]
I've never installed a package on conda either 😅

I simply use conda to install packages in conda environment to avoid install conflicts

I find this link that can be interresting : 
https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs.html

**Comment by vincentarelbundock** [comment]
Thanks a lot for the link. I looked at it, but I don't use conda, and most of it read like gibberish to me. Unfortunately, I think this would take too much time for me to do, so I probably won't do it myself.

I would be very happy to answer questions and support someone who would like to submit the package to `conda-forge`: https://conda-forge.org/

For someone familiar with conda, I don't think this would much work at all. But realistically, I'm not going to do that in the short run.

Thanks for trying the package out and raising the issue!

**Comment by vincentarelbundock** [comment]
The optimistic view is that many of my packages are already on the main conda repo, without me doing anything. So there's a good chance `tinytable` makes its way there magically in the future...

**Comment by JulieBlasquiz** [comment]
I fully understand

Thank you for taking the time to reply

Julie
