### ISSUE TITLE
Exporting a wide table to PDF truncates the output

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/tinytable#234]
This is a silly example, the real usecase is exporting a balance table made by `datasummary_balance()` to PDF.

``` r
library(tinytable)

# wide df
test <- cbind(mtcars[1, ], mtcars[1, ])

tt(test) |> 
  save_tt("foo.pdf")
#> Warning: Package tabularray Warning: Table width is too small, need 284.97998pt
#> more!
```

In the PDF output, the table is truncated. Maybe it's a limitation of the `standalone` package but it would be great to automatically fit the table.

**Comment by vincentarelbundock** [comment]
Does it work with the "resize" theme?

**Comment by vincentarelbundock** [comment]
That doesn't show up in the finale table, right?

Of course, it would be better to not display a warning there. But realistically, I'll probably prioritize other things with my limited dev time.

**Comment by etiennebacher** [comment]
> That doesn't show up in the finale table, right?

No, it doesn't show, the output is fine

> But realistically, I'll probably prioritize other things with my limited dev time.

Sure sure, no problem
