### ISSUE TITLE
multipage not working in PDF tutorial

### ISSUE THREAD

**Issue by andrewheiss** [vincentarelbundock/tinytable#236]
I've been struggling to get multipage working with Quarto, and it seems that the documentation is too.

The vignette at https://vincentarelbundock.github.io/tinytable/vignettes/tinytable_tutorial.pdf currently doesn't show multipage working:

<img width="561" alt="image" src="https://github.com/vincentarelbundock/tinytable/assets/73663/72bf2be0-2f84-48db-9a59-ef417a1d82a3">

The older tutorial vignette at https://vincentarelbundock.github.io/tinytable/vignettes/tutorial.pdf has it working:

<img width="615" alt="image" src="https://github.com/vincentarelbundock/tinytable/assets/73663/ccfb799c-07f1-469d-a23f-74916926289e">

**Comment by andrewheiss** [comment]
The LaTeX output seems to not be using `longtblr` anymore:

```r
tmp <- rbind(mtcars, mtcars)[, 1:6]

cap <- "A long 80\\% width table with repeating headers."

tt(tmp, width = .8, caption = cap) |>
  theme_tt("multipage", rowhead = 1) |> 
  print("latex")
```

```latex
\begin{talltblr}[         %% tabularray outer open
caption={},
caption={A long 80\% width table with repeating headers.},
]                     %% tabularray outer close
{                     %% tabularray inner open
width={0.8\linewidth},
colspec={X[]X[]X[]X[]X[]X[]},
rowhead=1,
}                     %% tabularray inner close
\toprule
mpg & cyl & disp & hp & drat & wt \\ \midrule %% TinyTableHeader
21.0 & 6 & 160.0 & 110 & 3.90 & 2.620 \\
21.0 & 6 & 160.0 & 110 & 3.90 & 2.875 \\
...
```

**Comment by vincentarelbundock** [comment]
Thanks a lot for the investigation. You put your finger right on it. Should be fixed now on Github.

Note that chunk options for caption and label do not work in Quarto with multipage table, as reported here: https://github.com/quarto-dev/quarto-cli/discussions/9332

You'll need to use the `caption` argument and insert `\\label{blahblah}` in the caption itself if you want references to work in LaTeX.

**Comment by andrewheiss** [comment]
Et voilà! Thanks!

<img width="1018" alt="image" src="https://github.com/vincentarelbundock/tinytable/assets/73663/26d7d72c-be1e-443d-9096-79a0e99c6780">

**Comment by vincentarelbundock** [comment]
Nice! now how do we avoid linebreaks? You could then use the `resize` theme to make it fit horizontally...

**Comment by andrewheiss** [comment]
Using landscape works well here

Add this to the preamble bc pandoc doesn't parse anything in between `\begin{}` and `\end{}`

```
\newcommand{\blandscape}{\begin{landscape}}
\newcommand{\elandscape}{\end{landscape}}
```

Then use those in the document:

````
\blandscape

```{r}
tt(...) |>
  theme_tt("multipage", rowhead = 1)
```

\elandscape
````

<img width="1120" alt="image" src="https://github.com/vincentarelbundock/tinytable/assets/73663/0a7e04d2-a706-480a-9809-8017ac3bf665">

(idk what's happening with the centering here for some of those columns 🤷‍♂️ )
