### ISSUE TITLE
typst: table captions dont work

### ISSUE THREAD

**Issue by aghaynes** [vincentarelbundock/tinytable#247]
Table captions don't seem to work for typst at the moment whether entered via tbl-cap nor the caption argument.

Here's an example using kable and two variations with `tt`:

```` 
---
title: "Untitled"
format: typst
execute:
  echo: false

---

```{r}
#| tbl-cap: MTCARS
mtcars |> head() |> knitr::kable()
```

```{r}
#| tbl-cap: MTCARS
mtcars |> head() |> tinytable::tt()
```

```{r}
#| tbl-cap: MTCARS
mtcars |> head() |> tinytable::tt(caption = "mtcars")
```
```` 

![image](https://github.com/vincentarelbundock/tinytable/assets/6594028/47eb4d77-dd2d-4b71-be82-35a6739dae46)

**Comment by vincentarelbundock** [comment]
You need to specify the `label` chunk option as well, not just `tbl-cap`. This is a Quarto quirk discussed here: https://github.com/quarto-dev/quarto-cli/issues/9369

**Comment by aghaynes** [comment]
Ah, OK, thanks! 

On a different note, maybe it would be nice to center align the table, as with kable?

Also, how about support for rotating tables?
![image](https://github.com/vincentarelbundock/tinytable/assets/6594028/cf21d051-276f-46a1-96bc-cc14c04fc5f9)

typst doesnt handle tables that are too wide (when rotated) for the page then though :( but maybe there's something that they can do

**Comment by vincentarelbundock** [comment]
Closing because I added a point of information in the FAQ document.
