### ISSUE TITLE
Typst: center tables by default

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#248]
> maybe it would be nice to center align the table, as with kable?

_Originally posted by @aghaynes in https://github.com/vincentarelbundock/tinytable/issues/247#issuecomment-2115098640_

**Comment by vincentarelbundock** [comment]
LaTeX does centering by default, so it would be nice to be consistent and center Typst tables by default too. 

What's the appropriate syntax? Should go in here: https://github.com/vincentarelbundock/tinytable/blob/main/inst/templates/typst.typ

**Comment by aghaynes** [comment]
```
#align(center,
[
#let nhead = 1;
....
]
)
```
This would conflict with #250 though... there i replace `out[1]` (`#[`) with `[` and prepend the rotate. If you switch to center aligned, I suppose you'd need to wrap the rotate in align instead. Or maybe there's a more elegant way (something along the lines of `gsub("#", "#rotate(-90deg,\\n[", out[1])`)

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion @aghaynes This was a good idea. Should be merged in Github dev version now.

**Comment by aghaynes** [comment]
This unfortunately doesnt seem to have worked... tables are still left aligned...
![image](https://github.com/vincentarelbundock/tinytable/assets/6594028/7a287091-133e-46f8-931a-0d07dafc2739)
![image](https://github.com/vincentarelbundock/tinytable/assets/6594028/a0576ff2-2c60-4edb-b1d0-a22b39d51394)

**Comment by aghaynes** [comment]
i think its interacting with the quarto stuff again... removing the tbl-cap and label seems to center align it... this is frustrating...

**Comment by vincentarelbundock** [comment]
Weird. This works on my computer:

````
---
format: typst
---

```{r}
packageVersion("tinytable")

library(tinytable)
tt(iris[1:3, 1:3], caption = "blah blah blah")
```


```{r}
#| tbl-cap: blah blah blah
#| label: tbl-blah

library(tinytable)
tt(iris[1:3, 1:3], caption = "blah blah blah")
```
````

![image](https://github.com/vincentarelbundock/tinytable/assets/987057/e0a9f79a-7323-4c05-a485-97e8e3f9cef3)

**Comment by aghaynes** [comment]
that does indeed work for me too... i'm sure i tested it like this though. 

Maybe it's the template i'm using then... that same code within the template i'm using is left aligned... i'll investigate...

**Comment by aghaynes** [comment]
it's the echo option!
````
---
format: typst
execute:
  echo: false
---

```{r}
packageVersion("tinytable")

library(tinytable)
tt(iris[1:3, 1:3], caption = "blah blah blah")
```


```{r}
#| tbl-cap: blah blah blah
#| label: tbl-blah

library(tinytable)
tt(iris[1:3, 1:3], caption = "blah blah blah")
```
````
![image](https://github.com/vincentarelbundock/tinytable/assets/6594028/a2ecf8c0-c7fc-4cba-b32c-9f33aa3a5c13)

**Comment by vincentarelbundock** [comment]
I have no idea why this would change things. Maybe you can inspect the raw `.typ` file.

**Comment by aghaynes** [comment]
no idea why, but adding an empty r block into the `.typ` does the trick (but it also add the grey box to the PDF)
````
#block[
```r
```
#figure([
````
The only difference between the code for these two figures is that r block (it's copy/pasted .typ code, not recompiled through knitr, only typst)
![image](https://github.com/vincentarelbundock/tinytable/assets/6594028/0e68b040-0e49-4837-a293-1592ae0326c2)
