### ISSUE TITLE
Rotating tables

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#249]
> Also, how about support for rotating tables?
![image](https://github.com/vincentarelbundock/tinytable/assets/6594028/cf21d051-276f-46a1-96bc-cc14c04fc5f9)

> typst doesnt handle tables that are too wide (when rotated) for the page then though :( but maybe there's something that they can do

_Originally posted by @aghaynes in https://github.com/vincentarelbundock/tinytable/issues/247#issuecomment-2115098640_

**Comment by vincentarelbundock** [comment]
Yes, I agree that rotating tables would be a nice feature. I would be happy to consider a Pull Request for this. Ideally, the functionality should cover LaTeX and Typst. It probably doesn't make sense in Markdown or HTML.

**Comment by aghaynes** [comment]
for reference: https://github.com/typst/typst/discussions/4148

**Comment by aghaynes** [comment]
i have example code somewhere for latex, but it relies on an additional latex package... which would need loading (in the header?). I'll see what i can do about a PR

**Comment by vincentarelbundock** [comment]
Lua filter for Typst: https://github.com/quarto-dev/quarto-cli/discussions/9705

Does not preserver the caption

**Comment by vincentarelbundock** [comment]
```
```{=typst}
#rotate(-90deg, reflow: true, [
```

```{r}
#| tbl-cap: blah blah blah
#| label: tbl-base
head(mtcars) |> tinytable::tt()
```

```{=typst}
])
```
```

**Comment by vincentarelbundock** [comment]
Using the development version of `tinytable`, we can now do: `tt(x) |> theme_tt("rotate", angle = 45)`
