### ISSUE TITLE
Typst: table placement

### ISSUE THREAD

**Issue by Nenuial** [vincentarelbundock/tinytable#259]
I was looking for a way to align the table on the left in a Typst document. If I am not mistaken, this isn't currently possible because the typst template hard codes `#align(center, …)` for the table.

It would be a nice feature if it were possible to decide on the table placement.

**Comment by marcboschmatas** [comment]
Not making promises but I'll try to have a look at it some time next week!

**Comment by Nenuial** [comment]
That would be great!
I'd be happy to have a look at it, but in the next few weeks it won't be possible for me.

**Comment by vincentarelbundock** [comment]
This is now possible in version 0.3.0.31 from Github:

````
---
format: typst
---

```{r} 
library(tinytable)
head(iris) |> 
    tt() |>
    theme_tt("placement", horizontal = "l") 
```
````
