### ISSUE TITLE
Input data.frame row.names dropped with no option to retain

### ISSUE THREAD

**Issue by rsbivand** [vincentarelbundock/tinytable#264]
At https://github.com/vincentarelbundock/tinytable/blob/26cd0888113cd43a390c9ba926d9d795dd682434/R/tt.R#L103 the row names get dropped. Is it worth trying to retain row names if the user needs them?

```
x <- mtcars[1:4, 1:5]
x
tt(x)
```

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion and for taking the time to look at the code!

What behavior do you think would be most intuitive and useful? Some options:

1. Always insert a new column with row names.
2. Always insert a new column with row names, unless they are equivalent to `1:nrow(x)`
3. Allow a global: `options(tinytable_row_names = TRUE)`
4. New argument: `row.names=TRUE=
5. New arguments `row.names` and `col.names` (as in `knitr::kable()`)

I'm trying to limit the number of new arguments in `tt()`, and I don't know if this is popular enough to justify it.

Thoughts?

**Comment by rsbivand** [comment]
3. is least invasive, so no new arguments, and works well in scripts and notebooks. If users then found it useful interactively, maybe re-visit, but I agree that limiting the argument count is important.
 
Motivation - I have some outputs in single-row data.frames that I'm stacking from a list with `do.call` (IIRC), that get row names for free, but got stuck there.

**Comment by rsbivand** [comment]
@vincentarelbundock thanks very much! Just in time for preparations for a talk for useR!
