### ISSUE TITLE
`theme_tt()`: Raw `tabular` without any `tabularray`

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#268]
> Tabularray is cool, but in the spirit of minimal package dependencies (and coauthors who don't like changing latex preambles) it might be nice to have a minimal latex theme that outputs raw _tabular_ code (without any formatting that depends on tabularray.)

_Originally posted by @mjdcurtis in https://github.com/vincentarelbundock/tinytable/issues/30#issuecomment-2158178124_

**Comment by vincentarelbundock** [comment]
In version 0.3.0.18 from Github, `theme_tt("tabular")` returns a pure `tabular` environment, without requiring `booktabs` or `tabularray`.

**Comment by vincentarelbundock** [comment]
This is fixed upstream in `tinytable`

**Comment by parasurama** [comment]
The theme_tt("tabular") uses \hline. Is it possible to replace \hline with \toprule and \bottomrule?

**Comment by vincentarelbundock** [comment]
@parasurama not currently, but if anyone is interested in implementing that, it would be pretty easy to modify this file:

https://github.com/vincentarelbundock/tinytable/blob/main/R/theme_tabular.R#L12
