### ISSUE TITLE
Quarto revealjs: disable CSS themeing added by Quarto and Reveal

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#284]
https://github.com/quarto-dev/quarto-cli/discussions/10068#discussioncomment-9829295

**Comment by grantmcdermott** [comment]
Watching this in case of downstream impacts. Fwiw we roll our own table CSS in the Quarto RevealJS "clean" theme. https://github.com/grantmcdermott/quarto-revealjs-clean/blob/0aa8273ad7c77b7f6a9d6ba5e9b7abd240bdc335/_extensions/clean/clean.scss#L244-L278

**Comment by vincentarelbundock** [comment]
https://stackoverflow.com/questions/78659964/add-code-to-html-header-in-quarto-without-modifying-the-preamble/78660732#78660732


````
You should be able to use `htmltools::htmlDependency()`

Like if I was trying to recreate `knitr::knit_meta_add(list(rmarkdown::html_dependency_font_awesome()))`, I could by:

```r
metadata <- list(htmltools::htmlDependency(
  name ="font-awesome", 
  version = "6.4.2", 
  src = list("fontawesome"), 
  stylesheet = c("css/all.min.css", "css/v4-shims.min.css"), 
  package = "fontawesome", 
  all_files = TRUE))

knitr::knit_meta_add(metadata)
```
````

**Comment by vincentarelbundock** [comment]
The dev version on Github now has a `theme_revealjs()` function. This will be the recommend way to style RevealJS tables in the future.

Examples here:

https://vincentarelbundock.github.io/tinytable/vignettes/notebooks.html#slides-revealjs
