### ISSUE TITLE
Typst: `align` array is too verbose

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#292]
One row of alignment array per cell is not great. Currently, the mechanism to overwrite defaults does not quite work, because `style_tt()` is called on a column-by-column sequence, rather than altogether, so we don't overwrite the defaults.

The Typst function to set alignment should also check the default array and not print the alignement array if it matches the default.

**Comment by DominikVogel** [comment]
I tested tinytable 0.3.0.20 and get another error. Sorry!

```
[typst]: Compiling test.typ to test.pdf...error: function `table` does not contain field `cell`
    ┌─ \\?\C:\Git\test\test.typ:299:14
    │
299 │   #show table.cell: it => {
    │               ^^^^
```

Replication code: https://github.com/vincentarelbundock/modelsummary/issues/787

No need to do that during your vaccation!

**Comment by vincentarelbundock** [comment]
Are you using Quarto pre-release and the latest Typist?  What versions exactly?

**Comment by DominikVogel** [comment]
Im using Quarto 1.4.549 and the Typst version that comes with RStudio 2024.04.2+764 (or Quarto?)

**Comment by vincentarelbundock** [comment]
That version of Quarto does not support the latest Typist. I think you should install pre-release

**Comment by DominikVogel** [comment]
Quarto 1.5.52 was just released. It works with this version. Thanks a lot!

**Comment by vincentarelbundock** [comment]
The dev version on Github generates much more efficient Typst code.
