### ISSUE TITLE
Unable to place tables in custom crossref environments in Quarto PDFs

### ISSUE THREAD

**Issue by andrewheiss** [vincentarelbundock/tinytable#293]
In Quarto, it's possible to create a custom crossref type for things like appendix tables. Here's a minimal reprex:

````
---
title: "Example"
format:
  pdf: default
  html: default
crossref:
  custom:
    - kind: float
      key: apptbl
      latex-env: apptbl
      reference-prefix: Table A
      space-before-numbering: false
      latex-list-of-description: Appendix Table
apptbl-cap-location: top
---

See @apptbl-testing

::: {#apptbl-testing}

```{r}
library(tinytable)

tt(mtcars[1:5,])
```

Caption goes here.

:::
````

{tinytable} works fine with custom crossrefs when rendering to HTML:

<img width="832" alt="image" src="https://github.com/vincentarelbundock/tinytable/assets/73663/ba8adca3-b0b4-402d-b885-db8aa329adb6">

&nbsp;

But when rendering to PDF, it causes an error:

```
ERROR: 
compilation failed- error
LaTeX Error: Not in outer par mode.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.240 \centering
                 

see testing.log for more information.
```

The line 240 it's complaining about is the `\centering` immediately after `\begin{table}`, which apparently isn't allowed there since it's already in a `\centering{}` environment right after the caption definition?

```latex
\begin{apptbl}

\caption{\label{apptbl-testing}Caption goes here.}

\centering{

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tinytable)}

\FunctionTok{tt}\NormalTok{(mtcars[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{,])}
\end{Highlighting}
\end{Shaded}

\begin{table}
\centering
\begin{tblr}[         %% tabularray outer open
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]Q[]Q[]Q[]Q[]Q[]Q[]Q[]Q[]},
}                     %% tabularray inner close
\toprule
mpg & cyl & disp & hp & drat & wt & qsec & vs & am & gear & carb \\ \midrule %% TinyTableHeader
21.0 & 6 & 160 & 110 & 3.90 & 2.620 & 16.46 & 0 & 1 & 4 & 4 \\
21.0 & 6 & 160 & 110 & 3.90 & 2.875 & 17.02 & 0 & 1 & 4 & 4 \\
22.8 & 4 & 108 &  93 & 3.85 & 2.320 & 18.61 & 1 & 1 & 4 & 1 \\
21.4 & 6 & 258 & 110 & 3.08 & 3.215 & 19.44 & 1 & 0 & 3 & 1 \\
18.7 & 8 & 360 & 175 & 3.15 & 3.440 & 17.02 & 0 & 0 & 3 & 2 \\
\bottomrule
\end{tblr}
\end{table}

}

\end{apptbl}%
```

**Comment by vincentarelbundock** [comment]
I don't have as much time to diagnose because vacation, but I don't think the problem is `\centering`. To illustrate, we can use the `finalize` argument of `style_tt()` to regex that bit out of the table, and it still breaks. In contrast, when using a raw `tabular` environment (using the latest `tinytable` 0.3.0.20), things seem to work fine.

So there seems to be a bad interaction between whatever fancy thing Quarto does and the `tblr` environment from `tabularray`. Not sure yet what it is...

Example:

```r
```{r}
library(tinytable)

packageVersion("tinytable")

# Good
tt(head(mtcars)) |> theme_tt("tabular") 

# Bad
clean <- function(x) {
    if (x@output == "latex") {
        x@table_string <- gsub("\\\\centering", "", x@table_string)
    }
    x
}
tt(head(mtcars)) |> style_tt(finalize = clean)

```

Requires `tinytable` from Github as of this morning.

**Comment by vincentarelbundock** [comment]
OK, I tracked down the problem, added a new feature to leverage as workaround, and documented all of this on the FAQ page: 

https://vincentarelbundock.github.io/tinytable/vignettes/faq.html#quarto

Thanks for the report. This is an interesting use-case. I wasn't aware we could do things like that.

**Comment by andrewheiss** [comment]
Great, thanks so much!

**Comment by brueckmann** [comment]
> OK, I tracked down the problem, added a new feature to leverage as workaround, and documented all of this on the FAQ page:
> 
> https://vincentarelbundock.github.io/tinytable/vignettes/faq.html#quarto
> 
> Thanks for the report. This is an interesting use-case. I wasn't aware we could do things like that.

I wanted to let you know, that this link doesn't work anymore. 

I came here, as of today, using tinytable_0.16.0.13 (see sessioninfo below), I still have the problem that the [Crossref Example](https://vincentarelbundock.github.io/tinytable/vignettes/notebooks.html#custom-crossref-styles) (or excluding theme_latex, as in [Andrew's post above](https://github.com/vincentarelbundock/tinytable/issues/293#issue-2382780435) does render only to HTML not to PDF because of the `\centering`. 


It yields the following error (in full): 

```
==> quarto preview tinytablecerossref.qmd --to pdf --no-watch-inputs --no-browse



processing file: tinytablecerossref.qmd
                                                                                                            
output file: tinytablecerossref.knit.md

pandoc 
  to: latex
  output-file: tinytablecerossref.tex
  standalone: true
  pdf-engine: lualatex
  variables:
    graphics: true
    tables: true
  default-image-extension: pdf
  
metadata
  documentclass: scrartcl
  classoption:
    - DIV=11
    - numbers=noendperiod
  papersize: letter
  header-includes:
    - \KOMAoption{captions}{tableheading}
  block-headings: true
  engines:
    - path: /Applications/RStudio.app/Contents/Resources/app/quarto/share/extension-subtrees/julia-engine/_extensions/julia-engine/julia-engine.js
  title: Crossref Example
  crossref:
    custom:
      - kind: float
        key: apptbl
        latex-env: apptbl
        reference-prefix: Table A
        space-before-numbering: false
        latex-list-of-description: Appendix Table
  apptbl-cap-location: top
  

Rendering PDF
running lualatex - 1
  This is LuaHBTeX, Version 1.24.0 (TeX Live 2026) 
   restricted system commands enabled.
  
updating tlmgr

updating existing packages
ERROR: 
compilation failed- error
LaTeX Error: Not in outer par mode.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.249 \centering
              


see tinytablecerossref.log for more information.
WARN: Error encountered when rendering files
```



```r
> sessionInfo()
R version 4.5.2 (2025-10-31)
Platform: aarch64-apple-darwin20
Running under: macOS Tahoe 26.3.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/London
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tinytable_0.16.0.13

loaded via a namespace (and not attached):
 [1] RColorBrewer_1.1-3 R6_2.6.1           farver_2.1.2       magrittr_2.0.5     glue_1.8.1         stringr_1.6.0      tibble_3.3.1       pkgconfig_2.0.3   
 [9] lifecycle_1.0.5    cli_3.6.6          scales_1.4.0       vctrs_0.7.3        compiler_4.5.2     boot_1.3-32        sampcompR_0.3.3    rstudioapi_0.19.0 
[17] tools_4.5.2        pillar_1.11.1      rlang_1.2.0        stringi_1.8.7     
```

**Comment by vincentarelbundock** [comment]
The FAQ moved here: https://vincentarelbundock.github.io/tinytable/vignettes/notebooks.html#quarto

**Comment by brueckmann** [comment]
> The FAQ moved here: https://vincentarelbundock.github.io/tinytable/vignettes/notebooks.html#quarto

Okay, thanks. It's just that directly under your link, there is this custom crossref example I just mentioned, that still doesn't render to PDF. Should I create a new issue?

**Comment by vincentarelbundock** [comment]
Yes, if you have read the details of the examples, including the mention of `theme_latex()` and it still doesn't work as describe, please file an issue with a fully reproducible example.
