### ISSUE TITLE
More themes

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#30]
+ [x] "striped-columns"
+ [x] "dark"
+ [x] "raw"
+ [x] More?

**Comment by strengejacke** [comment]
Something like we find in papers, e.g. only vertical lines to separate headers from content:
![image](https://github.com/vincentarelbundock/tinytable/assets/26301769/d0f2282d-88b8-48b7-b1d5-9fb4e4119452)
(https://academic.oup.com/eurpub/article/33/6/1148/7241576)

or

![image](https://github.com/vincentarelbundock/tinytable/assets/26301769/47785b3a-2f62-48f5-a0d2-8f640fda6ed9)
(https://www.frontiersin.org/articles/10.3389/fpubh.2022.844560/full)

That would include an option to place the caption at the top of the table.

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion @strengejacke. That's basically what we have as default currently for LaTeX and Word, no?

The same is difficult to achieve across platforms in HTML because of a Quarto issue: https://github.com/quarto-dev/quarto-cli/discussions/8444

I could still implement a change which gives us this classic look in HTML for standalone tables saved with `save_tt()`.

**Comment by strengejacke** [comment]
I mostly view HTML tables in the viewer and copy/paste to word. I'm rarely using Latex (not at all, actually), so it would be really nice to have such a theme for HTML.

**Comment by vincentarelbundock** [comment]
Yeah, I'm with you. This is important. In fact, I think this style should be default, so I changed the html default and added a "bootstrap" theme for the old style. The LaTeX and HTML tables are more similar now.

**Comment by vincentarelbundock** [comment]
See: https://vincentarelbundock.github.io/tinytable/vignettes/tutorial.html#themes

**Comment by strengejacke** [comment]
Nice, I think the custom css we can use in `style_tt()` should be sufficient to build own themes!

**Comment by vincentarelbundock** [comment]
Right, agreed! I think the only additional ones I need to implement are the "raw" themes, where I just return a pure HTML table, without any of the body or scripts or styles. Same with LaTeX: just return a tabular object. 

I'm sure some users will use that, and it's hard to remove stuff that was added already. For the rest, I think the styling function is probably sufficient for users to handle things.
