### ISSUE TITLE
Font selection for cells, headers, notes, etc.

### ISSUE THREAD

**Issue by botan** [vincentarelbundock/tinytable#302]
Thank you for this amazing package!

Sorry if this feature already exists, but I couldn't find it in the documentation. The only thing holding me back from fully migrating and using tinytable in production is not being able to use custom fonts. Are there any plans to enable this in the near future?

**Comment by vincentarelbundock** [comment]
Thanks for the kind words!

I'm curious about your use case. So far, I've taken the view that fonts are better set as a document property. Otherwise, people end up with tables with a different font from the text, and that is usually very ugly. Obviously, this is opinionated...

What output format are you using? If your are writing HTML tables, it is trivial to change the font using CSS (see tutorial).

**Comment by botan** [comment]
Thanks for the quick reply!

I use Quarto to generate Word documents, but the tricky point is my company's primary font is not monospace, hence it doesn't look great in tables for number alignments.

**Comment by botan** [comment]
Thanks for the quick reply!

I use Quarto for generating Word documents, but the tricky point is that my company's primary font is not monospace. Unsurprisingly, it doesn't look great in tables with number alignments. So, being able to specify a different font for the tables is quite handy in my case.

**Comment by vincentarelbundock** [comment]
Ah yes, I had not thought of that situation, but it makes total sense. Thanks for clarifying.

I don't want to make too many promises here. For HTML output, this would be relatively easy to add. For Word output, however, I expect this to be more difficult. The challenge is that `tinytable` creates a markdown table, and then uses Pandoc to convert it to a Word document. I have not researched this in detail, but I don't know of a way to use different fonts for different text in a pandoc-converted documented.

Setting a *global* font for the full table might be an easier goal to achieve in the medium run.

Note to self: If we do this, I'd like the solution to work in all output formats.

**Comment by botan** [comment]
Wonderful, thank you for considering!

**Comment by vincentarelbundock** [comment]
Unfotunately, this won't be possible for Word absent a **major** rewrite of the code base. Closing this as "wontfix".

Sorry to disappoint.

**Comment by botan** [comment]
No disappointment at all, thanks again!
