### ISSUE TITLE
Typst Math Compatibility as Quarto?

### ISSUE THREAD

**Issue by kazuyanagimoto** [vincentarelbundock/tinytable#311]
@vincentarelbundock , Thanks for your amazing work!

I love this powerful package, which works in HTML, LaTeX, and Typst with exactly the same syntax and its compatibility with each format by detecting the document type in Quarto.

I am just wondering if it is possible to support a math equation compatibility for Typst as Quarto.
Since the Math syntax in Typst is not compatible with LaTeX's, I am now preparing another dataframe for Typst.

I don't know how complex it could be, but it would be very nice feature if it supports a conversion from LaTeX syntax to Typst syntax as Quarto does.

**Comment by vincentarelbundock** [comment]
What happens if you just put in Typst-style math in a table and compile that to Typst?

Can you supply an example?

**Comment by vincentarelbundock** [comment]
Do you mean that tinytable should understand the full math syntax in Typst, the full math syntax in LaTeX, and provide a full features bi directional conversion utility to translate between them?

If I understood correctly, this would be an insanely difficult project for anyone, and is certainly out of scope for a table-drawing package.

**Comment by kazuyanagimoto** [comment]
Sorry for my confusing explanation. I understand that the full syntax support by one package is extremely tough. I am now wondering if it is possible to pass a math object to Quarto. Quarto can render most of the math from LaTeX → Typst in the text. So I just wonder if it is possible to utilize the feature for tables.

**Comment by vincentarelbundock** [comment]
Maybe enable Quarto data processing I. Format_tt(), but that removes some tinytable capabilities. Also not sure if it will work.
