### ISSUE TITLE
Add option `tinytable_markdown_use_gfm`?

### ISSUE THREAD

**Issue by kylebutts** [vincentarelbundock/tinytable#314]
Currently `tinytable` has gfm compliant markdown, but only when `knit_print` is detected (I just learned this while tryiing to reprex it not working). Would it be possible to use an option to turn on that behavior even when `knitr` is not detected?

**Comment by vincentarelbundock** [comment]
Hmm, can you clarify what gfm-compliant means? There's only one function to creat markdown grids, so I'm not sure what you'd want to turn on or off with this feature.

**Comment by kylebutts** [comment]
It's a subtle difference. Knitr produces a different table than `print("markdown")`. 

Running in REPL:
``` r
tinytable::tt(head(mtcars)) |> print("markdown")
```
+------+-----+------+-----+------+-------+-------+----+----+------+------+
| mpg  | cyl | disp | hp  | drat | wt    | qsec  | vs | am | gear | carb |
+======+=====+======+=====+======+=======+=======+====+====+======+======+
| 21.0 | 6   | 160  | 110 | 3.90 | 2.620 | 16.46 | 0  | 1  | 4    | 4    |
+------+-----+------+-----+------+-------+-------+----+----+------+------+
| 21.0 | 6   | 160  | 110 | 3.90 | 2.875 | 17.02 | 0  | 1  | 4    | 4    |
+------+-----+------+-----+------+-------+-------+----+----+------+------+
| 22.8 | 4   | 108  |  93 | 3.85 | 2.320 | 18.61 | 1  | 1  | 4    | 1    |
+------+-----+------+-----+------+-------+-------+----+----+------+------+
| 21.4 | 6   | 258  | 110 | 3.08 | 3.215 | 19.44 | 1  | 0  | 3    | 1    |
+------+-----+------+-----+------+-------+-------+----+----+------+------+
| 18.7 | 8   | 360  | 175 | 3.15 | 3.440 | 17.02 | 0  | 0  | 3    | 2    |
+------+-----+------+-----+------+-------+-------+----+----+------+------+
| 18.1 | 6   | 225  | 105 | 2.76 | 3.460 | 20.22 | 1  | 0  | 3    | 1    |
+------+-----+------+-----+------+-------+-------+----+----+------+------+ 


Running within a knitr context (rendering `.qmd` or running this with `reprex::reprex()`) yields (view raw md):
``` r
#| results: 'asis'
tinytable::tt(head(mtcars)) |> print("markdown")
```

| mpg  | cyl | disp | hp  | drat | wt    | qsec  | vs  | am  | gear | carb |
|------|-----|------|-----|------|-------|-------|-----|-----|------|------|
| 21.0 | 6   | 160  | 110 | 3.90 | 2.620 | 16.46 | 0   | 1   | 4    | 4    |
| 21.0 | 6   | 160  | 110 | 3.90 | 2.875 | 17.02 | 0   | 1   | 4    | 4    |
| 22.8 | 4   | 108  | 93  | 3.85 | 2.320 | 18.61 | 1   | 1   | 4    | 1    |
| 21.4 | 6   | 258  | 110 | 3.08 | 3.215 | 19.44 | 1   | 0   | 3    | 1    |
| 18.7 | 8   | 360  | 175 | 3.15 | 3.440 | 17.02 | 0   | 0   | 3    | 2    |
| 18.1 | 6   | 225  | 105 | 2.76 | 3.460 | 20.22 | 1   | 0   | 3    | 1    |

**Comment by vincentarelbundock** [comment]
`tinytable` can only produce "grid" style markdown tables, and not "pipe" style tables. See the difference in the pandoc docs: https://pandoc.org/chunkedhtml-demo/8.9-tables.html

What's happening is that when a `tinytable` is printed in a Rmarkdown document, the `knit_print` method is triggered. The *only* thing that does is add a `knit_asis` class to the table, but the underlying text is still in "grid style", with + signs and separators for every row. Then, `knitr` processes the file, detects the grid style table, and converts it to a pipe-style table.

The reason I picked "grid" as the markdown style is that it supports spanning columns and groups:

```markdown
+--------------+-------------+--------------+-------------+---------+
| a                          | b                                    |
+--------------+-------------+--------------+-------------+---------+
| Sepal.Length | Sepal.Width | Petal.Length | Petal.Width | Species |
+==============+=============+==============+=============+=========+
| 5.1          | 3.5         | 1.4          | 0.2         | setosa  |
+--------------+-------------+--------------+-------------+---------+
| 4.9          | 3.0         | 1.4          | 0.2         | setosa  |
+--------------+-------------+--------------+-------------+---------+
| 4.7          |             | 1.3          | 0.2         | setosa  |
+--------------+-------------+--------------+-------------+---------+
| 4.6          | 3.1         | 1.5          | 0.2         | setosa  |
+--------------+-------------+--------------+-------------+---------+
```

The downside of grid style is that it is not displayed well in Github issues. Beyond that, I don't know of any benefit of pipe style over grid style (maybe sparser look is good).

To support pipe style, we would need a function to convert the text representation, probably using regexes. This might not be super hard. Or it might be very hard to accommodate corner cases like colspans. I don't really know.

All this to say: it's not as easy as flipping a switch, and I'm not sure there is enough benefit to justify investing a ton of time in this. But if you or someone else wants to write the conversion function, I'm sure we can find a user interface that makes sense.

**Comment by kylebutts** [comment]
I think your changes reintroduced the `tinytable_markdown_hlines` bug. The disabling needs to go before `finalize` is called. 

I'll submit a PR, but would it make more sense to put this in `finalize_grid`:
```
    hlines <- get_option("tinytable_markdown_hlines", default = TRUE)
    if (isTRUE(hlines) && x@output != "gfm") {
      x <- grid_hlines(x)
    }
```

**Comment by vincentarelbundock** [comment]
You know, i don't actually like this option. The result is not a standards-compliant markdown table. The only reason it was there was for people who like a "sparser" look (the "grid" is heavy looking). But now that we have `gfm`, I think we should just remove that option.

**Comment by vincentarelbundock** [comment]
I doubt anyone used it, but this should probably still be noted as breaking change in NEWS

**Comment by kylebutts** [comment]
Okay will do that too. Do you think the pandoc conversion should be in `finalize_grid` or `build_tt`?

**Comment by vincentarelbundock** [comment]
I don't really have a strong view on this. As long as it works 😉
