### ISSUE TITLE
Excel and Powerpoint output

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#322]

**Comment by J-Moravec** [comment]
I would suggest a heavy use of the `openxlsx2` package. I worked with it before and it allows quite robust styling.

* Styling: https://janmarvin.github.io/openxlsx2/articles/openxlsx2_style_manual.html and https://janmarvin.github.io/openxlsx2/articles/conditional-formatting.html
* Image support: https://janmarvin.github.io/openxlsx2/articles/openxlsx2_charts_manual.html

Looks like a lot of styling could be mapped relatively easily in 1 to 1 fashion.

**Comment by vincentarelbundock** [comment]
That's interesting.

To be transparent, I'm not sure I'll work on this in the short run, since I don't use Excel myself, and because it feels a bit against the `tinytable` ethos of zero dependencies.

However, if someone cares about this feature and is willing to submit a fully-featured pull request, I'll be happy to review.

Thanks for bringing this up!

**Comment by J-Moravec** [comment]
Same same. The only time I am working with excel is when I am trying to work with other people's files.

But this feature would be on my wishlist: https://x.com/brentcrossman/status/1844412279263199427

Ability to download the tables as csv/excel would be rad.

**Comment by vincentarelbundock** [comment]
Oh, that is a cool feature. One easy solution would be to create a custom theme that does:

1. Save the content of `x@table_dataframe` to a CSV file in the current directory, with a unique name like `tinytable_UUID.csv`
2. Add a note automatically to `x@notes` with a link to that CSV file.

That would be like 5 lines of code and would be a nice way to display the downloadable at the bottom.

**Comment by vincentarelbundock** [comment]
I copied the link to useful Excel packages to the other thread. Closing here as duplicated, to consolidate discussion of Microsoft formats here: 

https://github.com/vincentarelbundock/tinytable/issues/335
