### ISSUE TITLE
`save_tt()` return path to the saved table

### ISSUE THREAD

**Issue by yjunechoe** [vincentarelbundock/tinytable#328]
It'd be convenient if `save_tt()` invisibly returned the path to the written file, so that the output can be quickly inspected with e.g., an additional pipe to `browseURL()`:

```r
tt(mtcars[1:4, 1:5]) |> 
  save_tt("mtcars.docx") |>
  browseURL()
```

Thanks!

**Comment by vincentarelbundock** [comment]
This is a great an easy suggestion. Thanks!

Merged in `main` on Github now. Will be part of the next release on CRAN.
