### ISSUE TITLE
Automatic conditional styling throws an error if the condition of the "which()" function is not met 

### ISSUE THREAD

**Issue by richardstoeckl** [vincentarelbundock/tinytable#331]
Thank you for this amazing package!

I think conditional styling is most useful in exploratory analysis, e.g. to highlight values over a required threshold.
Unfortunately, this seems to create some problems:

Let's say I use some device to measure my samples. I will then import the output of the device into R and create a table that shows me which samples fulfill the minimum requirements for the next steps and which samples fail. As these are measurements, they cannot be predicted beforehand.

```R
# simulate measurements 
df <- data.frame(Sample = c("Sample01", "Sample02","Sample03"),Measurement = c(runif(3, min=0.5, max=3)))

# highlight if the value is below 1 (=failed)
tt(df) %>%
    style_tt(i = which(df$Measurement < 1),j="Measurement",background = "darkred",color = "white")
```

This may produce two outcomes:

1. There is a sample with a failed measurement:
```R
df <- data.frame(Sample = c("Sample01", "Sample02","Sample03"),Measurement = c(0.5,0.8,1.2))
tt(df) %>%
    style_tt(i = which(df$Measurement < 1),j="Measurement",background = "darkred",color = "white")

# -> this works
```

2. All measurements are above 1
```R
df <- data.frame(Sample = c("Sample01", "Sample02","Sample03"),Measurement = c(1.3,2,1.2))
tt(df) %>%
    style_tt(i = which(df$Measurement < 1),j="Measurement",background = "darkred",color = "white")

# Error in `$<-.data.frame`(`*tmp*`, "bootstrap", value = "") : 
#   replacement has 1 row, data has 0
```

Is there a way to get this to work? I tried using ifelse() statements or creating a matrix with TRUE/FALSE values, but I couldn't find a working solution.

Thanks, 
Richard

**Comment by vincentarelbundock** [comment]
Thanks but closing as duplicate: https://github.com/vincentarelbundock/tinytable/issues/329#issuecomment-2308987626

**Comment by vincentarelbundock** [comment]
Sorry, I misunderstood the question.

Why can't you just use and `if()` statement?

```{r}
library(tinytable)
df <- data.frame(Sample = c("Sample01", "Sample02","Sample03"),Measurement = c(1.3,2,1.2))
tab <- tt(df)
if (any(df$Measurement < 1)) {
  tab <- style_tt(tab, i = which(df$Measurement < 1), j = "Measurement", background = "darkred", color = "white")
}
tab
```
