### ISSUE TITLE
`i = ...` and `group_tt()` get confusing

### ISSUE THREAD

**Issue by katossky** [vincentarelbundock/tinytable#334]
First thanks for tinytable !

1. I am not sure it is documented that the i index do count groups as rows.
2. Neither am I sure it is a good idea! First, this means that a table changes the indexation depending on whether it is grouped or not, and we need to compute the row in artifical ways instead of counting on logic of the table (like we cannot do `style_tt(i = iris$Species == 'verticolor', ...)` if the table has been grouped).

I do not have a good alternative, but maybe sth along `style_tt_groups()` or `style_tt(scope='groups')`.

**Comment by vincentarelbundock** [comment]
Thanks for the note.

I agree this is kind of confusing. I'll think about it, but my intuition is that finding a different solution will increase internal code complexity by a lot. In basically all format, we need to insert new rows of data in the actual table for groups, so we'd have to have special indexing everywhere to keep track of this, and bump up the indices accordingly. It's just much easier to tell LaTeX or JavaScript: "color the 5th row red", than "color the 5th row red unless there are groups, in which case..."

At the moment, I feel that we can probably live quirk, perhaps with improved documentation.

**Comment by katossky** [comment]
You're most probably right, since I don't know anything about your internal gears ! Just sharing my user experience.
