### ISSUE TITLE
`.docx`, `.xlsx`, `.ppt`: Colors, alignment, and other styles

### ISSUE THREAD

**Issue by katossky** [vincentarelbundock/tinytable#335]
I am trying to migrate from `gt` to your package, mainly because yours correctly exports numbered tables to docx in a quarto document.

However colors (font and background) do not seem to travel along to Word, which stops me for now.

**Comment by katossky** [comment]
(nor horizontal alignment ; bold is correctly rendered ; I did not test all types of styles)

**Comment by vincentarelbundock** [comment]
Thanks for trying out the package.

This is a known limitation, documented in `?style_tt()`

The problem is that Word tables are built by creating a markdown table and using Pandoc to convert to Word. Unfortunately, there is no syntax in markdown for colors or many other style elements.

**Comment by vincentarelbundock** [comment]
> I would suggest a heavy use of the `openxlsx2` package. I worked with it before and it allows quite robust styling.
> 
> * Styling: https://janmarvin.github.io/openxlsx2/articles/openxlsx2_style_manual.html and https://janmarvin.github.io/openxlsx2/articles/conditional-formatting.html
> * Image support: https://janmarvin.github.io/openxlsx2/articles/openxlsx2_charts_manual.html
> 
> Looks like a lot of styling could be mapped relatively easily in 1 to 1 fashion.

_Originally posted by @J-Moravec in https://github.com/vincentarelbundock/tinytable/issues/322#issuecomment-2398089999_
