### ISSUE TITLE
Quotation mark - Quarto - LaTeX interaction

### ISSUE THREAD

**Issue by dhicks** [vincentarelbundock/tinytable#336]
Some kind of interaction between (a) quotation marks in text cells and (b) generating a PDF via LaTeX (c) using Quarto  is causing opening quotation marks to not be converted to LaTeX's double backticks, ``.  

`mwe.qmd`: 
````
---
format:
    pdf:
        default
---

```{r}
library(tinytable)

dataf <- data.frame(
    id = 1:2,
    description = c(
        "Douglas, \"The Moral Responsibilities of Scientists\"",
        'Ottinger, "Buckets of Resistance" + screening of How to Survive a Plague'),
    stringsAsFactors = FALSE
)

## NB Doesn't matter whether special characters are being escaped or not
tt(dataf) |> 
    format_tt(escape = TRUE)
```
````

In both cells in `description` in the resulting PDF, the opening quotes appear as closing quotes.  This does not happen when using RMarkdown. (At first I thought this could be handled by tweaking the regex in `escape_text()`, but then I realized it's Quarto-specific. And I don't know enough about how Quarto and RMarkdown work under the hood!) 

[mwe.pdf](https://github.com/user-attachments/files/16897366/mwe.pdf)

**Comment by vincentarelbundock** [comment]
Have you looked at the raw .Tex file? With keep-tex

What does it look like? What would you expect tinytable to generate instead of that?

**Comment by dhicks** [comment]
I’ll try attaching the `tex` files to this email reply.  I did a quick diff using BBEdit, and the content of the tables + their environments look the same, but headers are somewhat different.  

￼￼
-----
Dan Hicks
Associate Professor and Chair
Department of Philosophy
University of California, Merced

Pronouns: they/them/their

**Comment by vincentarelbundock** [comment]
Thanks, but I can't see the diff. Maybe if you copy-paste it directly on Github?

What do you mean by "headers"?

`tinytable` only generates what is between `\begin{tblr}` and `\end{tblr}`. Anything outside of that is controlled by Quarto.

**Comment by vincentarelbundock** [comment]
I looked into this a bit and came to the conclusion that this is arguably a limitation of Quarto: It does not look inside LaTeX tables when looking for substitutions. 

Note that we get the same results with `gt` (developed by the same company as Quarto):

````
---
format: pdf
keep-tex: true
---

```{r}
library(tinytable)
library(knitr)
dataf <- data.frame(
    id = 1:2,
    description = c(
        "Douglas, \"The Moral Responsibilities of Scientists\"",
        'Ottinger, \"Buckets of Resistance" + screening of How to Survive a Plague')
)
gt(dataf)
```
````

However, we get OK quotes by outputing to markdown, presumably because Quarto has the ability to look inside markdown tables to do substitutions.


```
---
format: pdf
keep-tex: true
---

```{r}
library(tinytable)
library(knitr)

dataf <- data.frame(
    id = 1:2,
    description = c(
        "Douglas, \"The Moral Responsibilities of Scientists\"",
        'Ottinger, \"Buckets of Resistance" + screening of How to Survive a Plague')
)
tt(dataf) |> save_tt("gfm") |> knitr::asis_output()
```

**Comment by vincentarelbundock** [comment]
Of course, you can use backticks manually instead, though that's not a great solution if you need output to multiple formats.
