### ISSUE TITLE
Subset, rbind, and cbind

### ISSUE THREAD

**Issue by J-Moravec** [vincentarelbundock/tinytable#346]
Currently, this behaviour is undocumented and in some cases, unimplemented (or it returns nonsense).

I would like to:
  * subset rows or columns from table
  * rbind two tables together -- currently possible with `rbind`, just the default behaviour adds an additional header
  * cbind two tables together

This would allow preparing tables as chunks and adding them together, instead of having to prepare them all at once.

## User Case

I am currently preparing tables for two datasets, the code for the tables (including images) is identical, since they are summarizing the table in the same way.

But without the ability to merge them, I need to do quite a lot of complex wrangling instead to force them into `tinytable` format and prepare everything as a single big table.

**Comment by vincentarelbundock** [comment]
All of this sounds useful and sensible. 

Note that there is already support for various `rbind()` strategy via the `rbind2()` S4 method. See:

https://vincentarelbundock.github.io/tinytable/vignettes/tinytable.html#combination-and-exploration

We need to use `rbind2` because it allows extra arguments, whereas `rbind` does not (IIRC).

**Comment by vincentarelbundock** [comment]
In addition, we might want to implement methods for:

- `sort_by()`

**Comment by J-Moravec** [comment]
> All of this sounds useful and sensible.
> 
> Note that there is already support for various `rbind()` strategy via the `rbind2()` S4 method. See:
> 
> https://vincentarelbundock.github.io/tinytable/vignettes/tinytable.html#combination-and-exploration
> 
> We need to use `rbind2` because it allows extra arguments, whereas `rbind` does not (IIRC).

Sounds like all we need to do is define custom S3 method that calls rbind2 to have nicer interface.
And I need to read more on S4.

**Comment by vincentarelbundock** [comment]
I think I tried and `rbind()` and `cbind()` were not possible. It will have to be `rbind2.tinytable()` and `cbind2.tinytable()`. FWIW, I think the current interface for `rbind2()` is already quite "clean" and flexible.

It should be possible to define `subset.tinytable()` and  `sort_by.tinytable()`.

**Comment by J-Moravec** [comment]
I tested a few things and it looks like it would be fairly trivial to do subsetting in the same way the `rbind2` does:

```{r}
setMethod("[", signature("tinytable"), function(x, i){
    x@table_dataframe = x@table_dataframe[i]
    x@data = x@data[i]
    x@names = x@names[i]
    x@ncol = length(i)

    x
    })
```

So far, this enable subsetting, reordering columns, etc.

Few issues:

what is `tinytable@data`? It is used only 2x, once when nrows and ncols are set (if I remember correctly), and once when storing unformatted table in build_tt (or was it format_tt?)

After reordering, all the references set by `j=...` will be invalid and point to the old place.
This is obvious in hindsight, but caught me by surprise when my images ended up in totally different column.

I have noticed that `rbind2` doesn't care about these things as well, although it does printing into dataframe, which I haven't checked what it does under the hood and to images as well as lazy formatting.

No clue how to change it. Lazy reordering is bad since it will create a confusion on what are the correct columns and which columns should be referenced.

The only idea I have is to go into all these lazy formatted references for `j = ` (and later ` i = `) and modify the code (metaprgramming, yaaay!) so that they refer to the correct column, or drop them if the column was dropped.

**Comment by vincentarelbundock** [comment]
Frankly, I'm not sure what @data is. Maybe cruft from.past design?

Those are interesting issue, but they make wonder: is subsetting and reordering simply too dangerous? If it messes up our indices, there would be a lot of work necessary to handle that safely, which would add a lot of unnecessary code complexity. 

And whats the real benefit? Is it really better than subsetting data before feeding it to tt()?

To be honest, I suggested this in passing just because the methods are there. But "it's there" might not be sufficient just be sufficient justification.

In contrast, the benefits of cbind2() feel a bit clearer...

What do you think?

**Comment by J-Moravec** [comment]
I think I agree with you that the amount of work is substantial that one should really prepare the data and then call `tt()` and styles later.

The idea behind subsetting, reordering, and merging would be in ability creating big table in a modular way, with each part having custom styling.

But under the assumption that it is just too much work for it to matter, I don't see how `cbind2()` would be beneficial in this scenario?

Because if `cbind2()` is supposed to work on already styled tables, including images, we would have to parse the lazy calls anyway and modify the `j` value.

**Comment by vincentarelbundock** [comment]
Yes, I think that's right. Currently, `rbind2()` doesn't make any adjustment to indices. Likewise, `group_tt()` adds rows, but makes no adjustment to styling. 

So users already have to *know* what the final table looks like before they make decisions about styling. I've thought about different rules, but there are corner cases everywhere. And this has the benefit of clarity: `i` and `j` refer to indices in the final table.

Given that, I still think `cbind2()` might be useful, but I also feel it may not be super high priority. If it's too hard, probalby not a big deal.

**Comment by J-Moravec** [comment]
Given this discussion, I am closing the issue as not planned.

**Comment by vincentarelbundock** [comment]
Alright, sounds good. Glad we came to agreement on this, but sorry you had to waste some time looking at it before we got there.

Thanks for your efforts and interest!

**Comment by J-Moravec** [comment]
Nah, tis fine, no time wasted.

**Comment by statzhero** [comment]
Good discussion -- is this described in the package documentation?

**Comment by vincentarelbundock** [comment]
The currently implemented methods are discussed here: https://vincentarelbundock.github.io/tinytable/vignettes/tinytable.html#combination-and-exploration

**Comment by statzhero** [comment]
Maybe I missed it but it could be worth adding a paragraph on the “design philosophy” that every table should be fully formed before going into `tt()` if I understand that thread here. On Oct 5, 2024, at 11:25, Vincent Arel-Bundock ***@***.***> wrote:﻿
The currently implemented methods are discussed here: https://vincentarelbundock.github.io/tinytable/vignettes/tinytable.html#combination-and-exploration
