### ISSUE TITLE
Insert gap between rows/columns

### ISSUE THREAD

**Issue by J-Moravec** [vincentarelbundock/tinytable#347]
Perhaps this already exists, but I can't find it in the documentation.

I would like to insert gap between rows/columns.

For instance, to make grouped columns / rows more distinct.

## User case

I grouped bunch of columns and have them nice background coloured style. The issue here is that the columns are next to each other, and since there is no gap in the coloured square, it is hard to figure out to which group they belong to. I had to solve this manually by inserting a dummy column in-between. And gave up with cells.

**Comment by vincentarelbundock** [comment]
Added new `theme_tt("spacing")` option:

https://github.com/vincentarelbundock/tinytable/commit/46cbed793156c7f30ded6fefc0a5ce7909e37f95
