### ISSUE TITLE
Typst bolding issue

### ISSUE THREAD

**Issue by bsgallih12** [vincentarelbundock/tinytable#348]
I'm putting together a simple table with a spanning header above the main column titles. I want both the column titles and spanning header to be bolded. When I set the style function (i=-1:0, bold=TRUE) I get the spanning header bolded and the first column header bolded (that isn't covered by the spanning header) to be bolded in addition to the spanning header. But the columns under the header aren't bolded.

**Comment by vincentarelbundock** [comment]
Are you using the development version from Github?

```r
remotes::install_github("vincentarelbundock/tinytable")
library(tinytable)
packageVersion("tinytable")
```

If so, could you supply a reproducible example? Here are some tips to do that: https://marginaleffects.com/vignettes/help.html#getting-help

**Comment by bsgallih12** [comment]
table %>% tt(caption = "Study 1 Moderation Descriptives") %>%
  group_tt(j = list("Rare" = 2:4,
                    "Common" = 5:7)) %>%
  style_tt(i=0,j=1:7,align = "c") %>%
  style_tt(i=-1,j=1:7,bold = TRUE) %>%
  style_tt(i=0,j=1:7,bold = TRUE) %>%
  style_tt(i=0,j=2:7,italic = TRUE) %>%
  style_tt(i=1:6,j=2:7,align = "c")

**Comment by bsgallih12** [comment]
![image](https://github.com/user-attachments/assets/da059e5e-574b-41c8-bf4c-a00cf64383f9)

**Comment by vincentarelbundock** [comment]
With the latest version of `tinytable`, it works fine for me.

Note that a reproducible example requires data.

Here's a Quarto example:

````
---
format: typst
---

```{r}
library(tinytable)
head(iris) |>
    tt() |>
    group_tt(j = list("Sepal" = 1:2, "Petal" = 3:4)) |>
    style_tt(i = -1:0, bold = TRUE)
```
````

![Screenshot from 2024-09-23 13-15-51](https://github.com/user-attachments/assets/0f6254fb-723f-4f84-9fe2-01f4a3c7bd00)
