### ISSUE TITLE
Error related to Math part when rendering Quarto notebook to typst

### ISSUE THREAD

**Issue by feuerblitz7** [vincentarelbundock/tinytable#350]
I tried to render Math inside a table in a Quarto notebook, but when rendering it to typst format (pdf), I get an error:

```
[typst]: Compiling test.typ to test.pdf...error: unknown variable: rac
    ┌─ \\?\test.typ:354:4
    │
354 │ [$\frac{1}{2}$   ],
    │     ^^^
```
Any idea what could be wrong? My Quarto version is 1.5.57.

My `test.qmd` file:
```
---
title: "Test"
format: typst
---
```

```
library(tinytable)

dat <- data.frame(Math = c(
  "$x^2 + y^2 = z^2$",
  "$\\frac{1}{2}$"
))

tt(dat) |> style_tt(j = 1, align = "c")
```

**Comment by vincentarelbundock** [comment]
You are trying to compile a Typst table with LaTeX math in it. The math syntax in those two languages is different.

You might want to take a look at MiTeX, but I have never tried it myself. See: https://github.com/vincentarelbundock/tinytable/issues/345
