### ISSUE TITLE
Columns with same name

### ISSUE THREAD

**Issue by feuerblitz7** [vincentarelbundock/tinytable#352]
I have a table with some columns that shall have the same name. More specifically, the table has groups of columns that should share the same name (e.g., group 1 has columns min, max, and group 2 also has columns min, max). I cannot rename the columns on the dataframe directly since column names have to be unique. Is this possible to realize in some other way, e.g. in the formatting of the table?

**Comment by vincentarelbundock** [comment]
You can rename your columns on the data frame directly. Column names don't need to be unique in R.

**Comment by feuerblitz7** [comment]
> You can rename your columns on the data frame directly. Column names don't need to be unique in R.

Thanks! You are right; Not sure what I did wrong before...

**Comment by J-Moravec** [comment]
When you are creating a `data.frame` using the `data.frame()` function, or through `as.data.frame()` or `cbind()`, and `rbind()` etc., basically through anything that eventually calls `data.frame()`, it enforces columns to be unique, as well as other nonsense (converts `-` to `.`). You can fix that by doing `data.frame(..., check.names = FALSE)` or renaming columns afterwards.
