### ISSUE TITLE
Compact theme

### ISSUE THREAD

**Issue by statzhero** [vincentarelbundock/tinytable#353]
A simple feature request if it doesn't exist already: is there a compact theme? I'm thinking of a theme that reduces padding between rows and perhaps reduces the font size.

**Comment by vincentarelbundock** [comment]
Yes, I agree this would be nice. We would first need to implement this: https://github.com/vincentarelbundock/tinytable/issues/319

**Comment by vincentarelbundock** [comment]
`theme_spacing()` is now available in the development version of `tinytable` on Github.

Thanks for the feature request and for your patience!

```{r} 
library(tinytable)
head(iris) |>
    setNames(letters[1:5]) |>
    tt() |> 
    theme_tt("spacing", rowsep = .1, colsep = .5)
```

https://github.com/vincentarelbundock/tinytable/commit/46cbed793156c7f30ded6fefc0a5ce7909e37f95
