### ISSUE TITLE
Typst notes

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#357]
This generates an error:

```r
library(tinytable)
tt(head(iris), notes = "blah") |> print("typst")
```

Originally reported here https://github.com/vincentarelbundock/modelsummary/issues/819 by @DominikVogel

**Comment by vincentarelbundock** [comment]
@DominikVogel , this should be fixed by installing the development version of `tinytable` from Github.

**Comment by DominikVogel** [comment]
It works fine now. Thank you very much!
