### ISSUE TITLE
Cache images created by `plot_tt()`

### ISSUE THREAD

**Issue by J-Moravec** [vincentarelbundock/tinytable#358]
Making a report is iterative process.

In my report, I have a bunch of images for ~ 300 cells.

Every single time I translate the report to HTML, I recreate some 300 images (and translate them into 64bit encoded string).

This is very wasteful.

I would like if:

a) If images for the requested inputs exist, they won't be recreated.
b) If the 64bit encoding string for the requested inputs exists, they won't be recreated.

This won't only speedup the process when re-translating the table, but also prevents creating another sets of images when the table with images is simply printed.

**Comment by vincentarelbundock** [comment]
Sorry for the delayed response.

I thought about this for a while, but have decided against it. My current view is that this is probably best handled:

1. In a notebook by using the built-in `cache` functionality of Quarto or Rmarkdown.
2. In a script, by saving the tables and images to file and loading them in the document.

Also, I don't currently have the bandwidth to implement something like this, and my last attempts at caching in other contexts taught me that it is a surprisingly difficult and annoying project.

If someone wants to contribute caching, I'm happy to review. But there would have to be a compelling explanation for why options 1 and 2 above don't work at all in a significant number of applications (not just a single niche workflow), and then a very clean implementation that doesn't add much code complexity and causes no backward incompatibility.

Sorry to disapoint.
