### ISSUE TITLE
`align="d"` is not supported for rows: `style_tt(i = 1, align = "d")`

### ISSUE THREAD

**Issue by simonheb** [vincentarelbundock/tinytable#361]
The following code produces uncompilable LaTeX:

```
z <- data.frame(pi = c(pi * 100, pi * 1000, pi * 10000, pi * 100000))
tt(z) |>
    format_tt(j = 1, digits = 8, num_fmt = "significant_cell") |>
    style_tt(i = 1, align = "d") |> print("latex")
```

LaTeX:
```
\begin{table}
\centering
\begin{tblr}[         %% tabularray outer open
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]},
row{2}={si={table-format=-6.5,table-align-text-before=false,table-align-text-after=false,input-symbols={-,\*+()}},},
row{1}={guard},
}                     %% tabularray inner close
\toprule
pi \\ \midrule %% TinyTableHeader
314.15927 \\
3141.5927 \\
31415.927 \\
314159.27 \\
\bottomrule
\end{tblr}
\end{table} 
```

TeX Error message: "Undefined color `si'. \end".

I'm not sure what the ideal solution would be, since the user requests a rather unusual table configuration, but I guess it should be a t least some kind of error/warning.

**Comment by vincentarelbundock** [comment]
What did you insert in the LaTeX document preamble?

https://vincentarelbundock.github.io/tinytable/man/tt.html#latex-preamble

**Comment by vincentarelbundock** [comment]
aah, sorry, I misread your original post.

`align="d"` is only supported as a *column* format, not as a *row* format. 

I will add an informative error.

**Comment by vincentarelbundock** [comment]
Thanks again for the report. I finally got around to it. It's not a "solution" per se, but the next version is at least going to raise an informative warning:

``` r
library(tinytable)
z <- data.frame(pi = c(pi * 100, pi * 1000, pi * 10000, pi * 100000))
tt(z) |>
  format_tt(j = 1, digits = 8, num_fmt = "significant_cell") |>
  style_tt(i = 1, align = "d") |>
  print("latex")
#;-) Error: d column alignment can only be applied to entire columns. `i` must be `NULL`.
```
