### ISSUE TITLE
Packaged vignettes

### ISSUE THREAD

**Issue by svraka** [vincentarelbundock/tinytable#363]
Would it possible to package vignettes, so they're available from a user's installation? The website is very convenient but if the bleeding edge differs from the released version (or an even older version when working on a project managed via renv), differences due to new features can be confusing. 

If I'm not mistaken, Quarto is a supported vignette engine for [HTML](https://quarto-dev.github.io/quarto-r/articles/hello.html) and [PDF](https://quarto-dev.github.io/quarto-r/articles/hello-pdf.pdf).

**Comment by vincentarelbundock** [comment]
I don't think that CRAN allows Quarto vignettes.

**Comment by svraka** [comment]
The vignettes linked above are released on CRAN: https://cran.r-project.org/web/packages/quarto/index.html

**Comment by vincentarelbundock** [comment]
Oooh, nice, I didn't know that. Will see if I can make this work.

**Comment by vincentarelbundock** [comment]
I spent a couple hours getting this to look nice: https://github.com/vincentarelbundock/tinytable/pull/373

Unfortunately, the compiled size of the documentation is 12MB. The R docs say:

> As a general rule, neither data nor documentation should exceed 5MB (which covers several books). A CRAN package is not an appropriate way to distribute course notes, and authors will be asked to trim their documentation to a maximum of 5MB. 

https://cran.r-project.org/web/packages/policies.html#Source-packages

Also, small package size is a good feature.

I'm not sure it's worth it to do partial documentation as vignettes.

I agree with your main use-case: if the dev version differs substantially from the CRAN version, the website is annoying to navigate. The good news is that I think the package user interface will soon reach a much more stable phase, so there should be fewer discrepancies like the one you note.

I'll close this issue for now, but feel free to comment again if you want to push back.

And thanks for the suggestion. I learned about Quarto vignette, which was fun.

**Comment by svraka** [comment]
Thanks for taking the time. I agree, it's not worth the cost, especially as tinytable matures. Not to push back, just to add a few notes I you choose to revisit later (and you might have discovered these already).

I built the package from the `vignettes_cran` branch, and was surprised that every vignette file is huge, over 1M, even when containing just a few paragraphs of text, without any tables, graphics, or anything fancy. This is due to MathJax JS, which is included in every file (it was added recently in 070a186). Just as a crude test, dropping MathJax from every vignette file reduces the tar.gz to ~2.5M (there's maths notation in `format.qmd` but that is currently excluded). I'm sure I broke something but reducing the number of those included HTML raw attributes could reduce package size significantly. Is it possible to conditionally include them? Or would a single page HTML file -- like with `tinytable_tutorial.qmd` for LaTeX -- work, where a single MathJax refernce is sufficient?

**Comment by vincentarelbundock** [comment]
Thanks for the investigation, that's interesting.

Frankly, I'm still not sold on the project, even if we can make it work. It would be some additional work, and when I got it working, the vignette were really ugly because quarto disables bootstrap-related formatting options.

Since one of the main features I want to display is the nice visuals, I'm not a fan of the vignette display.

I'll keep thinking about it, but will treat as "wontfix" for now.

In any case, I thank you for the suggestion and the investigation. Sorry to disappoint.
