### ISSUE TITLE
Bookdown references

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#364]
https://x.com/opinonhaver/status/1848449037894140369

**Comment by eeemda** [comment]
fwiw, I ran into the exact same problem yesterday but chose to change my workflow (export tables to `.tex` and compile directly in a separate `latex` document and also think "I should probably take this opportunity to learn quarto") rather than troubleshooting further...

If useful, happy to pay more attention to what I was doing to reproduce.

**Comment by vincentarelbundock** [comment]
Yeah, if you can narrow things down, it would be cool.

I just don't have a good sense of whether people are still encouraged to use bookdown. Is it alive and well? If not, I might not invest a ton in debugging...

**Comment by eeemda** [comment]
Will do so over the next week or so, but as you mention might be the case for others, given new tools available, I was happy to think about moving away from using bookdown. It was never a core part of my workflow...

**Comment by jfieberg** [comment]
Thanks for your contributions! I ran into the same issue today.  I have a large book written in bookdown, made a few relatively minor changes and went to recompile. I noticed I lost all my references - both in the html and pdf versions of the book.  I suspect I'm not the only one in this boat.  Even if I switch to creating content using Quarto in the future - I'd rather not have to go back and reconfigure ~20 .Rmd files (and over 500 pages of content) to go from bookdown to quarto.  It would be awesome if tinytable worked with bookdown.

**Comment by vincentarelbundock** [comment]
Thanks for raising this issue and chiming in, everyone. I'm convinced that something should be done about this.

My "real" job is keeping me very busy these days, but I'll take a look when I find time. Of course, if someone finds a solution in the meantime, that would be great.

**Comment by vincentarelbundock** [comment]
I found a workaround. It's not exactly idea, but it seems to work. 

https://vincentarelbundock.github.io/tinytable/vignettes/notebooks.html#cross-references

Frankly, I have no idea what changed. Is it an upstream change or something in `tinytable`? No idea. So this will probably be it...

Thanks for the report and for chiming in.

**Comment by eeemda** [comment]
Have not tried this yet, but the example seems straightforward but also greater impetus to move to quarto...Thanks for this!

**Comment by jfieberg** [comment]
Thanks, Vincent!  Much appreciated.  Like Emmerich, I have not yet tried it
(though, it looks straightforward).  And, its also got me wondering if I
need to bite the bullet and move to quarto sooner than later.




*John Fieberg *(he/him/his)

Professor of Quantitative Ecology

Department of Fisheries, Wildlife, and Conservation Biology, University of
Minnesota

X: @FiebergJohn

Github: https://github.com/jfieberg

*https://fieberg-lab.cfans.umn.edu/ <https://fieberg-lab.cfans.umn.edu/>*


Interested in statistics? Please provide feedback on an open-source
statistics book that I have been developing. You can access the book by
clicking here. <https://statistics4ecologists-v2.netlify.app/index.html>


The Department of Fisheries, Wildlife, and Conservation Biology aims to
inspire and create solutions for biological conservation and management in
a diverse and changing world.
