### ISSUE TITLE
Documentation fix

### ISSUE THREAD

**Issue by saudiwin** [vincentarelbundock/tinytable#377]
So this is a relatively simple thing but it can cause quite a headache. I think the documentation needs to highlight more clearly that Quarto will fail to compile if caching is enabled with tinytable. Right now this is referenced in the tt documentation in parentheses:

"When rendering a document from Quarto or Rmarkdown directly to PDF, tinytable will populate the LaTeX preamble automatically with all the required packages **(except when code chunks are cached).** For standalone LaTeX documents, these commands should be inserted in the preamble manually:" (emphasis added)

I think this should be highlighted, like NOTE: Your document will fail to compile in Quarto if you enable caching and you use tinytable. 

I think the note should also include what I think is the most helpful (and very easy) fix:

NOTE: Your document will fail to compile in Quarto if you enable caching and you use tinytable due to missing Latex headers. To avoid this problem, set the option `cache: false` for the chunk(s) where you use tinytable.

I'm posting this as an issue as it took me a surprisingly long time to figure out what the issue was when it's a simple thing to fix and it is also kind of a big deal as Quarto is a big use case for tinytable.

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion and wording. I appreciate it.

4be6e6b88d8c390901326366cbb90e1474839721
