### ISSUE TITLE
`tt()` passing custom column names

### ISSUE THREAD

**Issue by kylebutts** [vincentarelbundock/tinytable#384]
Hi Vincent,

A pain point I am finding is that I have to write custom column names for my df object before piping to tt. Would it be hard to accept an argument to `tt` to provide custom column names?

**Comment by vincentarelbundock** [comment]
You can use `setNames()` from base `R` in a pipe. Or standard `colnames(tab)<-` otherwise.

See bottom page https://vincentarelbundock.github.io/tinytable/vignettes/tinytable.html#renaming-columns

Doesn't that cover most workflows?

**Comment by kylebutts** [comment]
This definitely suffices! Somehow I did not know of `base::setNames()` (I probably thought of it as a `data.table` function)
