### ISSUE TITLE
Replace conditional S3 method registration with NAMESPACE directive

### ISSUE THREAD

**Issue by MichaelChirico** [vincentarelbundock/tinytable#400]
https://github.com/vincentarelbundock/tinytable/blob/22602383c7151aec856fdcbcd8f141a8876ce068/R/zzz.R#L1-L5

Was searching around a bit after discovering the very nice approach in https://github.com/Rdatatable/data.table/pull/6589 and found {tinytable}. Because {tinytable} depends on R>=4.1.0, this can be replaced by `S3method(knitr::knit_print, tinytable)`.

I only didn't file the PR because I am not sure the right way to do so with {roxygen2} (do we need `@rawNamespace`?), and don't quite have time to dig deeper at the moment.

**Comment by vincentarelbundock** [comment]
Thanks again. This appears to work:

```r
#' @rawNamespace S3method(knitr::knit_print, tinytable)
```

https://github.com/vincentarelbundock/tinytable/commit/8fea1978b4538532c7684225d131dd6fcfbfdb27

**Comment by MichaelChirico** [comment]
Nice! FWIW we found roxygen2 has slightly cleaned support:

https://github.com/r-lib/lintr/commit/c3d2935d355230e28ee79c0a541fd137d005bc22
