### ISSUE TITLE
change table header bold formatting

### ISSUE THREAD

**Issue by ontam** [vincentarelbundock/tinytable#407]
Hi,

What are the default settings for the table header, and how can I change them? I tried modifying it like this, but it didn’t work. The first row is still bold. I tried with theme and without...

`tt(mtcars[1:5, 1:6],theme = "void") |> 
  style_tt(i=0,bold=FALSE)`

BTW, it’s a really nice package!

**Comment by vincentarelbundock** [comment]
Glad you like it!

What output format are you using? If HTML, the default is defined by Bootstrap, and `theme_void()` only removes lines, not the styling of the headers. This is controlled here: https://github.com/vincentarelbundock/tinytable/blob/main/R/theme_void.R#L31

Feel free to recommend a more appropriate Bootstrap class for the void theme if you find one.

**Comment by ontam** [comment]
I using quarto in R with format html and pdf (typst).

So, the solution for html is something like this? 
`tt(mtcars[1:5, 1:6]) |>  
style_tt(i = 0, bootstrap_css = "font-weight: normal;")`

What about pdf(typst)?

**Comment by vincentarelbundock** [comment]
Yep, that would work for HTML.

On my computer, headers are NOT bolded in typst or pdf, and I don't see a reason why they would be.

**Comment by ontam** [comment]
Sorry, my mistake. I only looked at the preview in RStudio. PDF output is correct.
