### ISSUE TITLE
Column header doesn't span multiple columns when exporting to latex_tabular

### ISSUE THREAD

**Issue by agazmararian** [vincentarelbundock/tinytable#408]
Hey Vincent,
When saving modelsummary output to latex_tabular, tinytable succeeds in having the cmidrule for the grouped column header, but it doesn't have the text itself span the specified columns. 

This screenshot shows the issue with the latex_tabular output.

<img width="482" alt="Screenshot 2024-12-20 at 5 36 05 PM" src="https://github.com/user-attachments/assets/2615e4e2-8283-450f-836f-cae32f610712" />

Here's the code for reference.

```{r}
file_vuln <- here("Output", "individual", "tables", "tab_lucid_vuln_ols.tex")
modelsummary(
  vuln,
  vcov = "HC2",
  stars = c("*" = .1, "**" = .05, "***" = .01),
  coef_map = coefmap,
  gof_map = gof_map,
  gof_omit = "R2|IC|Log|F|RMSE|Std",
  add_rows = data.frame(
    c("Region Fixed Effects"),
    c("No"),
    c("Yes"),
    c("Yes"),
    c("Yes")
  ),
  fmt = 2,
  escape = FALSE,
  output = "latex_tabular"
  ) %>%
  group_tt(j = list("DV: Vulnerability Beliefs" = 2:5)) %>%
  save_tt(file_vuln, overwrite = TRUE)
```

Thanks in advance for your help.

**Comment by vincentarelbundock** [comment]
Hey @agazmararian 

Unfortunately, spanning column labels are not supported and are unlikely to ever be supported with `latex_tabular`. If you don't want your table in a `table` environment, you can still get a `tabular`-like environment with spanning labels using the `theme_tt()` function. But note that this won't be a raw `tabular`, but instead a `tblr` environment. 

For all intents and purposes (ex: combining them in a single figure), those act the same. The `tblr` just requires the usual preamble declarations.

Ex:

```r
library(modelsummary)
library(tinytable)
mod <- list(
  lm(mpg ~ wt, mtcars),
  lm(mpg ~ wt + qsec, mtcars))
modelsummary(mod) |>
  group_tt(j = list("Blah blah" = 2:3)) |>
  theme_tt("tabular", style = "tabularray") |>
  print("latex")
```

**Comment by agazmararian** [comment]
Thanks!
