### ISSUE TITLE
Inline plots

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#44]

**Comment by jimgar** [comment]
Just adding my support for this as a feature.

**Comment by vincentarelbundock** [comment]
Would be nice if users could pass functions to inline their own `ggplot2` plots. 

And if we have a nice general interface, it's easy to create built-in "templates" in `tinytable`.

**Comment by vincentarelbundock** [comment]
This is now implemented and available on Github. There are a few basic plots available, but also a very flexible mechanism for users to define arbitrary inline plots using Base R or ggplot2.

See examples in the website tutorial.

![tinytable_gallery_05](https://github.com/vincentarelbundock/tinytable/assets/987057/869986d4-8fad-4bdd-8d5f-fd9bccbf60c2)
