### ISSUE TITLE
Conditional styling?

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/tinytable#47]
``` r
library(gt)
library(tinytable)

dat = mtcars[1:10, ]

gt(dat) %>%
  tab_style(
    style = cell_fill(color = "lightgreen"),
    locations = cells_body(rows = gear > carb)
  )
```
![image](https://github.com/vincentarelbundock/tinytable/assets/52219252/866451a5-b80e-4d8f-9746-2b5495d1fc24)

``` r

tt(dat) |> 
  style_tt(background = "lightgreen")
```
![image](https://github.com/vincentarelbundock/tinytable/assets/52219252/2e4a0a65-e646-4ecd-8ead-7db7133a10c6)

**Comment by etiennebacher** [comment]
Should have read the docs:

```r
tt(dat) |> 
  style_tt(
    i = gear_greater_rows,
    j = gear_greater_cols,
    background = "lightgreen"
  )

```

**Comment by vincentarelbundock** [comment]
This takes 91 characters, whereas your `gt` example takes 121 characters:

```r
tt(dat) |> 
  style_tt(
    i = which(dat$gear > dat$carb),
    background = "lightgreen")
```

**Comment by vincentarelbundock** [comment]
Yeah, exactly. Also, `j` accepts regular expressions for column names.
