### ISSUE TITLE
Consistent behaviour of `i` and `j` for grouping rows/columns

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/tinytable#54]
At a first glance, would you say it makes sense to make the `i` and `j` arguments for grouping consistent? i accepts integers with the starting position of each row, while j accepts the range (start-end). I think it's easier to remember if both behave in the same way.

**Comment by vincentarelbundock** [comment]
yeah that's a good point. consistency is important!

But what do we do with the end point of the range for row groups? ignore it?

![Screenshot 2024-01-14 063215](https://github.com/vincentarelbundock/tinytable/assets/987057/6809f72e-ff14-47e1-822f-2a3e5ad34212)

**Comment by strengejacke** [comment]
Based on the rendered example in the vignette, I didn't realize that you could leave some columns w/o header:

![image](https://github.com/vincentarelbundock/tinytable/assets/26301769/80d13af6-cd97-4340-bc61-3d2bfdbe7b06)

Then it makes sense to treat rows and columns differently.

**Comment by vincentarelbundock** [comment]
Ah yes, I should have opened an issue for this. Styles (alignment) doesn't work in HTML currently. It's clearer in PDF.

https://github.com/vincentarelbundock/tinytable/issues/56
