### ISSUE TITLE
Formatting numbers, dates, etc.

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/tinytable#60]

**Comment by jimgar** [comment]
Voicing support for this feature.

One thing in particular in gt that I’ve come to use a lot is “suffixing”, so that large numbers automatically get displayed as human readable. See https://gt.rstudio.com/reference/fmt_number.html

**Comment by vincentarelbundock** [comment]
Thanks for chiming in!

Yeah, that seems like a really useful feature. Formatting is a major priority for me, but I haven't quite figured out the user interface yet. I want something simple, with possibilities for extensions if users want.

I'll ping you when I have something to show in case you have feedback.

Thanks!

**Comment by jimgar** [comment]
That sounds superb. A simple interface that is flexible to user inputs would definitely be my preference. Really looking forward to seeing what you come up with :)

**Comment by vincentarelbundock** [comment]
@jimgar If you have a minute, please check out the new formatting function and vignette. I'd be curious to know what you think, keeping in mind that the scope is pretty minimalist.

https://vincentarelbundock.github.io/tinytable/vignettes/tutorial.html#formatting-numbers-dates-strings-etc.
