### ISSUE TITLE
`check_dependency()` doesn't print message when package is missing

### ISSUE THREAD

**Issue by wzbillings** [vincentarelbundock/tinytable#64]
When testing out `tinytable` in a new R project with `renv`, I get an unintuitive error message when trying to run `tt()` interactively. The following code:
```r
library(tinytable)
tt(mtcars[1:4, 1:4])
```
produces the following error message.
```
Error in interactive() && check_dependency("rstudioapi") : 
  invalid 'y' type in 'x && y
```

of course this error is easy to fix by installing `rstudioapi`, then everything works correctly.

I thought it would be slightly better to have a formal error message saying to install rstudioapi, so I checked the code and it looks like it was supposed to do that already.

Looking at the function `check_dependency()`, it appears that this is because if the package with the name passed to `check_dependency()` is not installed, then that function returns a character object instead of logical.

Maybe that function should have `stop(msg)` instead of `return(msg)` or something equivalent.

**Comment by wzbillings** [comment]
@vincentarelbundock Yes, now the check works as expected and the HTML window opens in a browser page instead of returning an error. (So much better than my suggestion of using `stop()` 😁.)

**Comment by vincentarelbundock** [comment]
!!!
