### ISSUE TITLE
Footnotes: add superscripts in specific cells?

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/tinytable#65]
``` r
library(gt)
library(tinytable)

gt(head(mtcars)) |>
  tab_footnote(
    footnote = "Miles per gallon.",
    locations = cells_column_labels(columns = mpg)
  )
```
![image](https://github.com/vincentarelbundock/tinytable/assets/52219252/7ead31d4-cd5b-4461-bfd7-0301c10f9eb2)

```r
tt(head(mtcars), notes = "Miles per gallon.")
```
![image](https://github.com/vincentarelbundock/tinytable/assets/52219252/5ef60501-f9bb-40ba-995d-7adc02f2307e)

**Comment by vincentarelbundock** [comment]
For now you have to do this semi-manually, but I'll leave this issue open and try to think of a better user interface.

```{r}
library(tinytable)
head(iris) |>
    dplyr::rename("Sepal.Length$\\dag$" = Sepal.Length) |>
    tt(notes = list("$\\dag$" = "Blah blah"))
```

![footnotes](https://github.com/vincentarelbundock/tinytable/assets/987057/92428582-79d1-4f15-9588-104abac5e633)

**Comment by strengejacke** [comment]
And for more than one footnote, a list of footnote/location would be great (not sure if gt supports this?).

**Comment by vincentarelbundock** [comment]
I think the syntax will eventually look like this:

```r
tt(head(mtcars), notes = 
  list("a" = list(i = 1, j = 2, text = "Miles per gallon."),
       "b" = list(i = 1, j = 4, text = "Other footnote.")
))
```

**Comment by vincentarelbundock** [comment]
This feature is now available on Github. Thanks for the suggestion!

https://vincentarelbundock.github.io/tinytable/vignettes/tutorial.html#footnotes
