### ISSUE TITLE
HTML version of tutorial is missing some formatting applied to tables

### ISSUE THREAD

**Issue by bvancil** [vincentarelbundock/tinytable#71]
First, let me say that I love how this package separates the content from the presentation, and you've done a fabulous amount of work!

As I was browsing <https://vincentarelbundock.github.io/tinytable/vignettes/tutorial.html>, I noticed that the tables were missing some of the applied formatting. For example, the alignments in this cell didn't match what I would expect:

![2024-01-16 12_20_57-Window](https://github.com/vincentarelbundock/tinytable/assets/1388508/6b0ee455-24e7-4963-a567-a6b95dbec166)

As another example, the i = 2, j = 3 cell was missing formatting in this cell:
![2024-01-16 12_22_52-Window](https://github.com/vincentarelbundock/tinytable/assets/1388508/cdabcbde-cf51-4854-bc9f-2777ff4b7a66)

Perhaps it's a browser-specific issue? I'm using Chrome 120.0.6099.217  for Windows.

Thanks for all your work!

**Comment by vincentarelbundock** [comment]
Well that's embarrassing: I pushed a major change at 1AM (bad idea!) and broke everything.

I just rolled back to an earlier version, and the website looks more reasonable.

Now that the repo is public, I'll switch to a more "normal" workflow with feature branches, continuous integration, etc. Hopefully this won't happen anymore.

**Comment by vincentarelbundock** [comment]
Thanks for the note!
