### ISSUE TITLE
Tinytable doesn't play well with quarto

### ISSUE THREAD

**Issue by Nenuial** [vincentarelbundock/tinytable#87]
First let me say that I find tinytable amazing. It's probably the first table package I encounter that offers fullwidth in PDF without having to resort to weird tricks ! And that's already a strong argument for me to try to adopt it.

I came across a problem on one of my quarto websites (it's private so I can't share a link). The website uses a *darkly* theme. When using tinytable on a page, the theme of the pages gets completely bungled.

In the HTML tinytable adds:
```html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
```
If I delete this part, then it works fine.

Am I missing something to avoid bootstrap beeing "reloaded"?

**Comment by Nenuial** [comment]
I just saw now that you have the open issue #86. It's probably linked I guess.

**Comment by Nenuial** [comment]
Great, thanks!

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/tinytable/commit/46e4bc6e768b7e5c523a9b10039ee9a381b5edc9 should prevent `tinytable` from loading a new Bootstrap when the file is rendered by `knitr`. I believe this should cover all Rmarkdown and Quarto contexts.

Bootstrap is still loaded when saving standalone HTML.

@Nenuial could you see if it now works on your website?

**Comment by Nenuial** [comment]
Works great, thanks!
