### ISSUE TITLE
Feature request : format markdown in cells

### ISSUE THREAD

**Issue by Nenuial** [vincentarelbundock/tinytable#91]
A feature that would really be great is something akin to gt's [`fmt_markdown()`](https://gt.rstudio.com/reference/fmt_markdown.html).

I don't know how complex this could be, especially considering the different output formats, but it would be a really nice feature.

**Comment by vincentarelbundock** [comment]
Yes, this sounds like a useful feature and it should be easy to implement.

Notes to self: In `format_tt()` add a `markdown` argument which calls `commonmark::markdown_html()` or `commonmark::markdown_latex()` depending on the output format. Keep as markdown for Word. Dont' forget to `assert_dependency()`

**Comment by vincentarelbundock** [comment]
@Nenuial this is now supported. See the Markdown section of the tutorial for examples
