### ISSUE TITLE
Indention of notes

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/tinytable#99]
When I indent subgroups and add footnotes to the table, the footnote is indented, too. Wouldn't it be better to have no indention for the footnote, same as for the title?

```r
library(tinytable)
library(ggeffects)

data(efc, package = "ggeffects")
efc <- datawizard::to_factor(efc, c("c172code", "c161sex"))
fit <- lm(barthtot ~ c161sex * c172code + c160age, data = efc)

pr <- ggpredict(fit, terms = c("c161sex", "c172code"))
out <- format(pr, group_name = TRUE)

row_header_pos <- which(!duplicated(out$groups))
row_header_labels <- as.list(stats::setNames(row_header_pos, as.vector(out$groups[row_header_pos])))
out$groups <- NULL

for (i in 2:length(row_header_pos)) {
  row_header_pos[i] <- row_header_pos[i] + (i - 1)
}

tt(out, caption = "Predicted values of Barthel Index", notes = "test") |>
  group_tt(i = row_header_labels, indent = 4) |>
  style_tt(i = row_header_pos, italic = TRUE)
```

![image](https://github.com/vincentarelbundock/tinytable/assets/26301769/8fc83bc1-09e1-4843-89f4-3b23208fba73)

**Comment by vincentarelbundock** [comment]
Hmm, maybe, I don't have a strong view. I think I indented a reflexively because it looked weird when the first group did not start on row 1. Try it with i starting at 3 and youll see what I mean.

But you may be right, not sure.

**Comment by strengejacke** [comment]
> because it looked weird when the first group did not start on row 1

I'm not quite sure I understand. The footnote is printed as last table row (just above the caption), so how does this affect where the first group starts? And since the "footnote" is not part of the table _data_, I think it's a bit confusing if this row is indented as well (I'm talking about the row with `test` in it).

> Try it with i starting at 3 and youll see what I mean.

What do you mean by this?

**Comment by vincentarelbundock** [comment]
Sorry, I got confused because in LaTeX I actually indent headers as well, and also the rows that are not part of a group.

Is you proposal that we should never indent either headers or footers?

![Screenshot_20240123-084818.png](https://github.com/vincentarelbundock/tinytable/assets/987057/1b8d1a8e-fe1f-4bcb-8179-56ffb88447dc)

**Comment by strengejacke** [comment]
In my opinion, this is the confusing part (for HTML output):

![image](https://github.com/vincentarelbundock/tinytable/assets/26301769/2651895f-843a-4de2-9e4b-cf62b4fc8146)

You see data rows have a small indent (indention? what's the noun in English?), the caption has not (not part of the _data_). The _footnote_, at a first glance, seems to be part of the _data rows_, because it's also indented. I think caption and footnotes should both never be indented.

**Comment by vincentarelbundock** [comment]
I am convinced. 

Crazy week but I'll try to make the change as soon as possible.

**Comment by vincentarelbundock** [comment]
Should be fixed now.

```{r}
library(tinytable)
x <- mtcars[1:5, 1:4]
tt(x, notes = list("hello", "world")) |> 
    group_tt(i = list("a" = 2, "b" = 4), indent = 4)
```

![Screenshot 2024-01-23 235819](https://github.com/vincentarelbundock/tinytable/assets/987057/f01b796f-d2f9-4508-bad8-e3d6f27d4c61)
